"""Code generation for the AI Delivery "generate" stage.

A pluggable provider turns a build request's spec into generated source files:

* :class:`TemplateProvider` — deterministic, dependency-free, works with no API
  key. Produces a real, runnable starter scaffold for the target type. This is the
  honest baseline: it always works and is fully tested.
* :class:`LLMProvider` — calls a configured LLM (Anthropic / OpenAI-style) to
  generate the app from the spec. Active only when ``codegen_api_key`` is set. The
  HTTP call is isolated in :func:`llm_complete` so it can be mocked in tests and
  swapped per provider; nothing here fabricates model output.

:func:`get_codegen_provider` picks the provider from settings.
"""

from __future__ import annotations

import json
import typing
import urllib.request
from dataclasses import dataclass, field
from typing import Protocol

from app.core.config import Settings
from app.modules.aidelivery.models import BuildTargetType

_SYSTEM = (
    "You are an expert engineer. Generate a COMPLETE, self-contained single-file "
    "web app as one HTML document (inline CSS + JS, no build step, no external "
    "packages except CDN links). Do not use localStorage. Output ONLY the raw HTML."
)


@dataclass
class GeneratedArtifact:
    """The output of a generation run."""

    provider: str
    summary: str
    files: dict[str, str] = field(default_factory=dict)


class CodeGenProvider(Protocol):
    """A provider that generates source files from a spec."""

    name: str

    def generate(
        self, spec: str, target_type: BuildTargetType, tech_stack: str = ""
    ) -> GeneratedArtifact: ...


# ---------------------------------------------------------------------------
# Template provider (no key required)
# ---------------------------------------------------------------------------
def _html_scaffold(title: str, spec: str, kind: str) -> str:
    safe = (spec or "Your app").strip().replace("<", "&lt;").replace(">", "&gt;")
    return f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>{title}</title>
<style>
  :root {{
    --ink:#14161f; --mute:#5b6b85; --accent:#3b6ff6; --bg:#f5f7fa; --card:#fff;
  }}
  * {{ box-sizing:border-box; }}
  body {{
    margin:0; font-family:system-ui,Arial,sans-serif;
    background:var(--bg); color:var(--ink);
  }}
  header {{ background:var(--ink); color:#fff; padding:22px 24px; }}
  h1 {{ margin:0; font-size:22px; }}
  main {{ max-width:820px; margin:28px auto; padding:0 20px; }}
  .card {{
    background:var(--card); border:1px solid #e4ecf6;
    border-radius:12px; padding:20px;
  }}
  button {{
    background:var(--accent); color:#fff; border:none; border-radius:8px;
    padding:10px 16px; font-size:15px; cursor:pointer;
  }}
  .muted {{ color:var(--mute); }}
</style>
</head>
<body>
  <header><h1>{title}</h1></header>
  <main>
    <div class="card">
      <p class="muted">Starter scaffold for a {kind}.
        Generated by ETIP AI Delivery (template provider).</p>
      <p><strong>Spec:</strong> {safe}</p>
      <p>Configure an LLM provider (set <code>CODEGEN_API_KEY</code>)
        to have ETIP generate the full app from this spec.</p>
      <button onclick="document.getElementById('out').textContent='It works.'">Try it</button>
      <p id="out" class="muted"></p>
    </div>
  </main>
</body>
</html>
"""


def _api_scaffold(spec: str) -> dict[str, str]:
    safe = (spec or "").strip()
    main = (
        '"""Generated API service scaffold (ETIP AI Delivery, template provider)."""\n\n'
        "from fastapi import FastAPI\n\n"
        'app = FastAPI(title="Generated Service")\n\n\n'
        '@app.get("/health")\n'
        "def health() -> dict[str, str]:\n"
        '    return {"status": "ok"}\n\n\n'
        '@app.get("/")\n'
        "def root() -> dict[str, str]:\n"
        f'    return {{"service": {json.dumps(safe or "Generated service")}}}\n'
    )
    return {"main.py": main, "requirements.txt": "fastapi\nuvicorn[standard]\n"}


class TemplateProvider:
    """Deterministic scaffold generator — always available, no key needed."""

    name = "template"

    def generate(
        self, spec: str, target_type: BuildTargetType, tech_stack: str = ""
    ) -> GeneratedArtifact:
        stacked = scaffold_for_stack(spec, tech_stack)
        if stacked is not None:
            return stacked
        if target_type is BuildTargetType.API_SERVICE:
            return GeneratedArtifact(
                provider=self.name,
                summary="Generated a FastAPI service scaffold (main.py + requirements.txt).",
                files=_api_scaffold(spec),
            )
        titles = {
            BuildTargetType.WEBSITE: "Website",
            BuildTargetType.WEB_APP: "Web App",
            BuildTargetType.MOBILE_APP: "Mobile Web App",
            BuildTargetType.OTHER: "App",
        }
        kind = target_type.value.replace("_", " ")
        return GeneratedArtifact(
            provider=self.name,
            summary=f"Generated a single-file {kind} scaffold (index.html).",
            files={"index.html": _html_scaffold(titles.get(target_type, "App"), spec, kind)},
        )


# ---------------------------------------------------------------------------
# LLM provider (requires a configured key)
# ---------------------------------------------------------------------------
def llm_complete(url: str, headers: dict[str, str], body: dict[str, object]) -> str:
    """POST a completion request and return the model's text.

    Isolated so tests can mock it; supports Anthropic-style responses (a ``content``
    list of blocks) and OpenAI-style (``choices[0].message.content``).
    """
    req = urllib.request.Request(
        url, data=json.dumps(body).encode(), headers=headers, method="POST"
    )
    with urllib.request.urlopen(req, timeout=60) as resp:  # noqa: S310
        data = json.loads(resp.read().decode())
    if isinstance(data.get("content"), list):  # Anthropic
        return "".join(b.get("text", "") for b in data["content"] if b.get("type") == "text")
    choices = data.get("choices")  # OpenAI-style
    if isinstance(choices, list) and choices:
        return str(choices[0].get("message", {}).get("content", ""))
    return ""


def _strip_fences(text: str) -> str:
    t = (text or "").strip()
    if t.startswith("```"):
        t = t.split("\n", 1)[-1]
        if t.endswith("```"):
            t = t[: t.rfind("```")]
    return t.strip()


# ---------------------------------------------------------------------------
# Depth: stack-aware prompts + multi-file parsing for LLM generation
# ---------------------------------------------------------------------------
_FRONTEND_STACKS = {
    "static-html",
    "react",
    "vue",
    "svelte",
    "angular",
    "nextjs",
    "remix",
    "sveltekit",
    "elm",
}
_MOBILE_STACKS = {"flutter", "react-native", "swiftui"}
_DATA_STACKS = {"data-python", "r", "julia", "sql"}
_BACKEND_STACKS = {
    "python-fastapi",
    "python-fastapi-sqlmodel",
    "python-flask",
    "python-django",
    "node-express",
    "nestjs",
    "go-http",
    "go-gin",
    "java-spring",
    "java-spring-jpa",
    "kotlin-ktor",
    "dotnet-minimal",
    "ruby-sinatra",
    "php",
    "php-laravel",
    "rust-axum",
    "elixir",
    "clojure",
    "fsharp",
    "dart-server",
    "scala",
}


def build_prompt(tech_stack: str, target_type: BuildTargetType, spec: str) -> str:
    """Build a rich, stack-aware code-generation prompt for the LLM provider."""
    kind = target_type.value.replace("_", " ")
    lead = "You are an expert software engineer. Build a complete, runnable " + kind
    if tech_stack:
        lead += f" using {tech_stack}"
    lead += "."
    if spec:
        lead += f"\n\nRequirements:\n{spec}"
    if tech_stack in _BACKEND_STACKS:
        depth = (
            "Include a data model, full CRUD endpoints (list, create, read, update, delete) "
            "with input validation, a database layer (use SQLite by default), JWT-based "
            "authentication (register, login, and a protected route), and a test file. "
            "Organise the code into multiple files."
        )
    elif tech_stack in _FRONTEND_STACKS:
        depth = (
            "Include a list view, a create/edit form with client-side validation, state "
            "management, and calls to a REST API. Organise into components across multiple "
            "files and include a test."
        )
    elif tech_stack in _MOBILE_STACKS:
        depth = (
            "Include a list screen, a detail/create screen, navigation, state management, "
            "and a test."
        )
    elif tech_stack in _DATA_STACKS:
        depth = (
            "Include data loading, a transformation/analysis step, a clear summary or output, "
            "and a test where applicable."
        )
    else:
        depth = (
            "Produce a complete, correct, runnable artifact with sensible structure and a "
            "test where applicable."
        )
    tail = (
        "\n\nReturn ONLY a JSON object mapping relative file paths to their full file "
        "contents. No prose, no markdown, no code fences. Example: "
        '{"path/to/file": "...file contents..."}.'
    )
    return lead + "\n\n" + depth + tail


def _default_filename(target_type: BuildTargetType, tech_stack: str) -> str:
    if tech_stack in _FRONTEND_STACKS or target_type in (
        BuildTargetType.WEB_APP,
        BuildTargetType.WEBSITE,
    ):
        return "index.html"
    if tech_stack.startswith("python"):
        return "main.py"
    return "GENERATED.md"


def _parse_generated_files(
    raw: str, target_type: BuildTargetType, tech_stack: str
) -> dict[str, str]:  # noqa: E501
    """Parse an LLM response into a {path: content} map, or fall back to one file."""
    try:
        data = json.loads(raw)
    except (json.JSONDecodeError, ValueError):
        data = None
    if (
        isinstance(data, dict)
        and data
        and all(isinstance(k, str) and isinstance(v, str) for k, v in data.items())
    ):
        return dict(data)
    return {_default_filename(target_type, tech_stack): raw}


class LLMProvider:
    """Generates via a configured LLM. Active only when an API key is set."""

    name = "llm"

    def __init__(self, settings: Settings) -> None:
        self._settings = settings
        self.name = settings.codegen_provider

    def generate(
        self, spec: str, target_type: BuildTargetType, tech_stack: str = ""
    ) -> GeneratedArtifact:
        s = self._settings
        headers = {
            "Content-Type": "application/json",
            "x-api-key": s.codegen_api_key,
            "anthropic-version": "2023-06-01",
            "authorization": f"Bearer {s.codegen_api_key}",
        }
        body: dict[str, object] = {
            "model": s.codegen_model,
            "max_tokens": s.codegen_max_tokens,
            "system": _SYSTEM,
            "messages": [{"role": "user", "content": build_prompt(tech_stack, target_type, spec)}],
        }
        raw = _strip_fences(llm_complete(s.codegen_base_url, headers, body))
        files = _parse_generated_files(raw, target_type, tech_stack)
        return GeneratedArtifact(
            provider=self.name,
            summary=f"Generated with {self.name} ({s.codegen_model}) \u2014 {len(files)} file(s).",
            files=files,
        )


def get_codegen_provider(settings: Settings) -> CodeGenProvider:
    """Return the configured provider — LLM when a key is set, else template."""
    if settings.codegen_provider != "template" and settings.codegen_api_key:
        return LLMProvider(settings)
    return TemplateProvider()


# ---------------------------------------------------------------------------
# Tech-stack scaffolds — broaden AI codegen across programming technologies
# ---------------------------------------------------------------------------
def _first_line(spec: str) -> str:
    text = (spec or "Generated by ETIP AI Delivery.").strip()
    return (text.splitlines()[0] if text else "App")[:200]


def _sc_react(s: str) -> dict[str, str]:
    note = _first_line(s)
    return {
        "package.json": '{\n  "name": "app",\n  "private": true,\n  "scripts": {"dev": "vite", "build": "vite build"},\n  "dependencies": {"react": "^18.2.0", "react-dom": "^18.2.0"},\n  "devDependencies": {"vite": "^5.0.0", "@vitejs/plugin-react": "^4.0.0"}\n}\n',  # noqa: E501
        "index.html": '<!doctype html><html><head><meta charset="utf-8"><title>App</title></head>\n<body><div id="root"></div><script type="module" src="/src/main.jsx"></script></body></html>\n',  # noqa: E501
        "src/main.jsx": 'import React from "react";\nimport { createRoot } from "react-dom/client";\nimport App from "./App.jsx";\ncreateRoot(document.getElementById("root")).render(<App />);\n',  # noqa: E501
        "src/App.jsx": f'export default function App() {{\n  return <main style={{{{padding:24,fontFamily:"system-ui"}}}}><h1>App</h1><p>{note}</p></main>;\n}}\n',  # noqa: E501
    }


def _sc_vue(s: str) -> dict[str, str]:
    note = _first_line(s)
    return {
        "package.json": '{\n  "name": "app",\n  "scripts": {"dev": "vite"},\n  "dependencies": {"vue": "^3.4.0"},\n  "devDependencies": {"vite": "^5.0.0", "@vitejs/plugin-vue": "^5.0.0"}\n}\n',  # noqa: E501
        "index.html": '<!doctype html><html><head><meta charset="utf-8"><title>App</title></head>\n<body><div id="app"></div><script type="module" src="/src/main.js"></script></body></html>\n',  # noqa: E501
        "src/main.js": 'import { createApp } from "vue";\nimport App from "./App.vue";\ncreateApp(App).mount("#app");\n',  # noqa: E501
        "src/App.vue": f'<template><main style="padding:24px;font-family:system-ui"><h1>App</h1><p>{note}</p></main></template>\n<script setup></script>\n',  # noqa: E501
    }


def _sc_svelte(s: str) -> dict[str, str]:
    note = _first_line(s)
    return {
        "package.json": '{\n  "name": "app",\n  "scripts": {"dev": "vite"},\n  "devDependencies": {"svelte": "^4.2.0", "vite": "^5.0.0", "@sveltejs/vite-plugin-svelte": "^3.0.0"}\n}\n',  # noqa: E501
        "src/App.svelte": f'<main style="padding:24px;font-family:system-ui"><h1>App</h1><p>{note}</p></main>\n',  # noqa: E501
    }


def _sc_flask(s: str) -> dict[str, str]:
    return {
        "app.py": 'from flask import Flask, jsonify\n\napp = Flask(__name__)\n\n\n@app.get("/health")\ndef health():\n    return jsonify(status="ok")\n\n\nif __name__ == "__main__":\n    app.run(port=8000)\n',  # noqa: E501
        "requirements.txt": "flask>=3.0\n",
        "README.md": f"# Flask service\n\n{_first_line(s)}\n",
    }


def _sc_express(s: str) -> dict[str, str]:
    return {
        "server.js": 'const express = require("express");\nconst app = express();\napp.use(express.json());\napp.get("/health", (_req, res) => res.json({ status: "ok" }));\napp.listen(8000, () => console.log("listening on :8000"));\n',  # noqa: E501
        "package.json": '{\n  "name": "service",\n  "main": "server.js",\n  "scripts": {"start": "node server.js"},\n  "dependencies": {"express": "^4.19.0"}\n}\n',  # noqa: E501
        "README.md": f"# Express service\n\n{_first_line(s)}\n",
    }


def _sc_go(s: str) -> dict[str, str]:
    return {
        "main.go": 'package main\n\nimport (\n\t"encoding/json"\n\t"net/http"\n)\n\nfunc main() {\n\thttp.HandleFunc("/health", func(w http.ResponseWriter, _ *http.Request) {\n\t\tjson.NewEncoder(w).Encode(map[string]string{"status": "ok"})\n\t})\n\thttp.ListenAndServe(":8000", nil)\n}\n',  # noqa: E501
        "go.mod": "module app\n\ngo 1.22\n",
        "README.md": f"# Go service\n\n{_first_line(s)}\n",
    }


def _sc_spring(s: str) -> dict[str, str]:
    return {
        "pom.xml": "<project><modelVersion>4.0.0</modelVersion><groupId>com.app</groupId><artifactId>app</artifactId><version>0.1.0</version>\n<parent><groupId>org.springframework.boot</groupId><artifactId>spring-boot-starter-parent</artifactId><version>3.2.0</version></parent>\n<dependencies><dependency><groupId>org.springframework.boot</groupId><artifactId>spring-boot-starter-web</artifactId></dependency></dependencies></project>\n",  # noqa: E501
        "src/main/java/com/app/Application.java": 'package com.app;\nimport org.springframework.boot.SpringApplication;\nimport org.springframework.boot.autoconfigure.SpringBootApplication;\nimport org.springframework.web.bind.annotation.*;\n\n@SpringBootApplication\n@RestController\npublic class Application {\n  public static void main(String[] a) { SpringApplication.run(Application.class, a); }\n  @GetMapping("/health") public String health() { return "{\\"status\\":\\"ok\\"}"; }\n}\n',  # noqa: E501
        "README.md": f"# Spring Boot service\n\n{_first_line(s)}\n",
    }


def _sc_dotnet(s: str) -> dict[str, str]:
    return {
        "Program.cs": 'var builder = WebApplication.CreateBuilder(args);\nvar app = builder.Build();\napp.MapGet("/health", () => new { status = "ok" });\napp.Run();\n',  # noqa: E501
        "app.csproj": '<Project Sdk="Microsoft.NET.Sdk.Web"><PropertyGroup><TargetFramework>net8.0</TargetFramework></PropertyGroup></Project>\n',  # noqa: E501
        "README.md": f"# .NET minimal API\n\n{_first_line(s)}\n",
    }


def _sc_sinatra(s: str) -> dict[str, str]:
    return {
        "app.rb": 'require "sinatra"\nrequire "json"\n\nget "/health" do\n  content_type :json\n  { status: "ok" }.to_json\nend\n',  # noqa: E501
        "Gemfile": 'source "https://rubygems.org"\ngem "sinatra"\n',
        "README.md": f"# Sinatra service\n\n{_first_line(s)}\n",
    }


def _sc_php(s: str) -> dict[str, str]:
    note = _first_line(s)
    return {
        "index.php": f'<?php\nif ($_SERVER["REQUEST_URI"] === "/health") {{\n  header("Content-Type: application/json");\n  echo json_encode(["status" => "ok"]);\n  exit;\n}}\n?>\n<!doctype html><html><body><h1>App</h1><p><?= htmlspecialchars("{note}") ?></p></body></html>\n'  # noqa: E501
    }


def _sc_rust(s: str) -> dict[str, str]:
    note = _first_line(s)
    return {
        "src/main.rs": f'fn main() {{\n    println!("App: {note}");\n}}\n',
        "Cargo.toml": '[package]\nname = "app"\nversion = "0.1.0"\nedition = "2021"\n\n[dependencies]\n',  # noqa: E501
    }


def _sc_flutter(s: str) -> dict[str, str]:
    note = _first_line(s)
    return {
        "lib/main.dart": f'import "package:flutter/material.dart";\n\nvoid main() => runApp(const App());\n\nclass App extends StatelessWidget {{\n  const App({{super.key}});\n  @override\n  Widget build(BuildContext c) => MaterialApp(\n    home: Scaffold(body: Center(child: Text("{note}"))),\n  );\n}}\n',  # noqa: E501
        "pubspec.yaml": "name: app\nenvironment:\n  sdk: '>=3.0.0 <4.0.0'\ndependencies:\n  flutter:\n    sdk: flutter\n",  # noqa: E501
    }


def _sc_react_native(s: str) -> dict[str, str]:
    note = _first_line(s)
    return {
        "App.js": f'import {{ Text, View }} from "react-native";\nexport default function App() {{\n  return (<View style={{{{flex:1,justifyContent:"center",alignItems:"center"}}}}><Text>{note}</Text></View>);\n}}\n',  # noqa: E501
        "package.json": '{\n  "name": "app",\n  "dependencies": {"react": "18.2.0", "react-native": "0.74.0"}\n}\n',  # noqa: E501
    }


def _sc_angular(s: str) -> dict[str, str]:
    note = _first_line(s)
    return {
        "package.json": '{\n  "name":"app",\n  "scripts":{"start":"ng serve"},\n  "dependencies":{"@angular/core":"^17.0.0","@angular/platform-browser":"^17.0.0","rxjs":"^7.8.0","zone.js":"^0.14.0"}\n}\n',  # noqa: E501
        "src/main.ts": 'import { bootstrapApplication } from "@angular/platform-browser";\nimport { AppComponent } from "./app.component";\nbootstrapApplication(AppComponent);\n',  # noqa: E501
        "src/app.component.ts": f'import {{ Component }} from "@angular/core";\n@Component({{ selector:"app-root", standalone:true, template:"<h1>App</h1><p>{note}</p>" }})\nexport class AppComponent {{}}\n',  # noqa: E501
    }


def _sc_nextjs(s: str) -> dict[str, str]:
    note = _first_line(s)
    return {
        "package.json": '{\n  "name":"app",\n  "scripts":{"dev":"next dev","build":"next build"},\n  "dependencies":{"next":"^14.0.0","react":"^18.2.0","react-dom":"^18.2.0"}\n}\n',  # noqa: E501
        "app/page.tsx": f"export default function Page() {{\n  return <main style={{{{padding:24}}}}><h1>App</h1><p>{note}</p></main>;\n}}\n",  # noqa: E501
        "app/layout.tsx": "export default function Layout({ children }: { children: React.ReactNode }) {\n  return (<html><body>{children}</body></html>);\n}\n",  # noqa: E501
    }


def _sc_nestjs(s: str) -> dict[str, str]:
    return {
        "package.json": '{\n  "name":"service",\n  "scripts":{"start":"nest start"},\n  "dependencies":{"@nestjs/core":"^10.0.0","@nestjs/common":"^10.0.0","@nestjs/platform-express":"^10.0.0","reflect-metadata":"^0.2.0","rxjs":"^7.8.0"}\n}\n',  # noqa: E501
        "src/main.ts": 'import { NestFactory } from "@nestjs/core";\nimport { AppModule } from "./app.module";\nasync function bootstrap(){ const app = await NestFactory.create(AppModule); await app.listen(8000); }\nbootstrap();\n',  # noqa: E501
        "src/app.module.ts": 'import { Module, Controller, Get } from "@nestjs/common";\n@Controller()\nclass AppController { @Get("health") health(){ return { status: "ok" }; } }\n@Module({ controllers: [AppController] })\nexport class AppModule {}\n',  # noqa: E501
        "README.md": f"# NestJS service\n\n{_first_line(s)}\n",
    }


def _sc_django(s: str) -> dict[str, str]:
    return {
        "manage.py": 'import os, sys\nif __name__ == "__main__":\n    os.environ.setdefault("DJANGO_SETTINGS_MODULE", "app.settings")\n    from django.core.management import execute_from_command_line\n    execute_from_command_line(sys.argv)\n',  # noqa: E501
        "app/settings.py": 'SECRET_KEY = "dev"\nDEBUG = True\nROOT_URLCONF = "app.urls"\nALLOWED_HOSTS = ["*"]\nINSTALLED_APPS = ["django.contrib.contenttypes", "django.contrib.auth"]\n',  # noqa: E501
        "app/urls.py": 'from django.http import JsonResponse\nfrom django.urls import path\nurlpatterns = [path("health", lambda r: JsonResponse({"status": "ok"}))]\n',  # noqa: E501
        "requirements.txt": "django>=5.0\n",
    }


def _sc_ktor(s: str) -> dict[str, str]:
    return {
        "src/main/kotlin/Application.kt": 'import io.ktor.server.engine.*\nimport io.ktor.server.netty.*\nimport io.ktor.server.application.*\nimport io.ktor.server.response.*\nimport io.ktor.server.routing.*\n\nfun main() {\n  embeddedServer(Netty, port = 8000) {\n    routing { get("/health") { call.respondText("{\\"status\\":\\"ok\\"}") } }\n  }.start(wait = true)\n}\n',  # noqa: E501
        "build.gradle.kts": 'plugins { kotlin("jvm") version "1.9.0"; application }\ndependencies { implementation("io.ktor:ktor-server-netty:2.3.0") }\napplication { mainClass.set("ApplicationKt") }\n',  # noqa: E501
    }


def _sc_laravel(s: str) -> dict[str, str]:
    note = _first_line(s)
    return {
        "routes/web.php": f'<?php\nuse Illuminate\\Support\\Facades\\Route;\nRoute::get("/", fn() => "{note}");\nRoute::get("/health", fn() => response()->json(["status" => "ok"]));\n',  # noqa: E501
        "composer.json": '{\n  "require": {"laravel/framework": "^11.0"}\n}\n',
    }


def _sc_swiftui(s: str) -> dict[str, str]:
    note = _first_line(s)
    return {
        "App.swift": "import SwiftUI\n\n@main\nstruct MyApp: App {\n  var body: some Scene { WindowGroup { ContentView() } }\n}\n",  # noqa: E501
        "ContentView.swift": f'import SwiftUI\n\nstruct ContentView: View {{\n  var body: some View {{ Text("{note}").padding() }}\n}}\n',  # noqa: E501
    }


def _sc_data_python(s: str) -> dict[str, str]:
    note = _first_line(s)
    return {
        "analysis.py": f'"""{note}"""\nimport pandas as pd\n\n\ndef main() -> None:\n    df = pd.DataFrame({{"x": [1, 2, 3], "y": [2, 4, 6]}})\n    print(df.describe())\n\n\nif __name__ == "__main__":\n    main()\n',  # noqa: E501
        "requirements.txt": "pandas>=2.0\nscikit-learn>=1.3\n",
    }


def _sc_remix(s: str) -> dict[str, str]:
    note = _first_line(s)
    return {
        "package.json": '{\n  "name":"app",\n  "scripts":{"dev":"remix dev"},\n  "dependencies":{"@remix-run/node":"^2.5.0","@remix-run/react":"^2.5.0","react":"^18.2.0","react-dom":"^18.2.0"}\n}\n',  # noqa: E501
        "app/routes/_index.tsx": f"export default function Index() {{\n  return <main style={{{{padding:24}}}}><h1>App</h1><p>{note}</p></main>;\n}}\n",  # noqa: E501
    }


def _sc_sveltekit(s: str) -> dict[str, str]:
    note = _first_line(s)
    return {
        "package.json": '{\n  "name":"app",\n  "scripts":{"dev":"vite dev"},\n  "devDependencies":{"@sveltejs/kit":"^2.0.0","svelte":"^4.2.0","vite":"^5.0.0"}\n}\n',  # noqa: E501
        "src/routes/+page.svelte": f'<main style="padding:24px"><h1>App</h1><p>{note}</p></main>\n',
    }


def _sc_gin(s: str) -> dict[str, str]:
    return {
        "main.go": 'package main\n\nimport "github.com/gin-gonic/gin"\n\nfunc main() {\n\tr := gin.Default()\n\tr.GET("/health", func(c *gin.Context) { c.JSON(200, gin.H{"status": "ok"}) })\n\tr.Run(":8000")\n}\n',  # noqa: E501
        "go.mod": "module app\n\ngo 1.22\n\nrequire github.com/gin-gonic/gin v1.9.1\n",
    }


def _sc_axum(s: str) -> dict[str, str]:
    return {
        "src/main.rs": 'use axum::{routing::get, Router, Json};\nuse serde_json::json;\n\n#[tokio::main]\nasync fn main() {\n    let app = Router::new().route("/health", get(|| async { Json(json!({"status":"ok"})) }));\n    let listener = tokio::net::TcpListener::bind("0.0.0.0:8000").await.unwrap();\n    axum::serve(listener, app).await.unwrap();\n}\n',  # noqa: E501
        "Cargo.toml": '[package]\nname = "app"\nversion = "0.1.0"\nedition = "2021"\n\n[dependencies]\naxum = "0.7"\ntokio = { version = "1", features = ["full"] }\nserde_json = "1"\n',  # noqa: E501
    }


def _sc_fastapi_sqlmodel(s: str) -> dict[str, str]:
    return {
        "main.py": 'from fastapi import FastAPI\nfrom sqlmodel import Field, SQLModel, create_engine\n\n\nclass Item(SQLModel, table=True):\n    id: int | None = Field(default=None, primary_key=True)\n    name: str\n\n\nengine = create_engine("sqlite:///app.db")\nSQLModel.metadata.create_all(engine)\napp = FastAPI()\n\n\n@app.get("/health")\ndef health() -> dict[str, str]:\n    return {"status": "ok"}\n',  # noqa: E501
        "requirements.txt": "fastapi>=0.110\nsqlmodel>=0.0.16\nuvicorn>=0.29\n",
    }


def _sc_spring_jpa(s: str) -> dict[str, str]:
    return {
        "pom.xml": "<project><modelVersion>4.0.0</modelVersion><groupId>com.app</groupId><artifactId>app</artifactId><version>0.1.0</version>\n<parent><groupId>org.springframework.boot</groupId><artifactId>spring-boot-starter-parent</artifactId><version>3.2.0</version></parent>\n<dependencies><dependency><groupId>org.springframework.boot</groupId><artifactId>spring-boot-starter-data-jpa</artifactId></dependency><dependency><groupId>com.h2database</groupId><artifactId>h2</artifactId></dependency></dependencies></project>\n",  # noqa: E501
        "src/main/java/com/app/Item.java": "package com.app;\nimport jakarta.persistence.*;\n@Entity\npublic class Item { @Id @GeneratedValue Long id; String name; }\n",  # noqa: E501
        "src/main/java/com/app/Application.java": "package com.app;\nimport org.springframework.boot.SpringApplication;\nimport org.springframework.boot.autoconfigure.SpringBootApplication;\n@SpringBootApplication\npublic class Application { public static void main(String[] a){ SpringApplication.run(Application.class, a);} }\n",  # noqa: E501
    }


def _sc_shell(s: str) -> dict[str, str]:
    note = _first_line(s)
    return {
        "main.sh": f'#!/usr/bin/env bash\nset -euo pipefail\n\n# {note}\necho "status: ok"\n',
        "README.md": f"# Shell script\n\n{note}\n",
    }


def _sc_c(s: str) -> dict[str, str]:
    note = _first_line(s)
    return {
        "main.c": f'#include <stdio.h>\n\n/* {note} */\nint main(void) {{\n    printf("status: ok\\n");\n    return 0;\n}}\n',  # noqa: E501
        "Makefile": "app: main.c\n\tcc -Wall -o app main.c\n",
    }


def _sc_cpp(s: str) -> dict[str, str]:
    note = _first_line(s)
    return {
        "main.cpp": f'#include <iostream>\n\n// {note}\nint main() {{\n    std::cout << "status: ok" << std::endl;\n    return 0;\n}}\n',  # noqa: E501
        "CMakeLists.txt": "cmake_minimum_required(VERSION 3.16)\nproject(app)\nadd_executable(app main.cpp)\n",  # noqa: E501
    }


def _sc_kotlin(s: str) -> dict[str, str]:
    return {
        "src/main/kotlin/Main.kt": 'fun main() {\n    println("status: ok")\n}\n',
        "build.gradle.kts": 'plugins { kotlin("jvm") version "1.9.0"; application }\napplication { mainClass.set("MainKt") }\n',  # noqa: E501
    }


def _sc_scala(s: str) -> dict[str, str]:
    return {
        "src/main/scala/Main.scala": '@main def run(): Unit = println("status: ok")\n',
        "build.sbt": 'scalaVersion := "3.3.1"\nname := "app"\n',
    }


def _sc_elixir(s: str) -> dict[str, str]:
    return {
        "mix.exs": 'defmodule App.MixProject do\n  use Mix.Project\n  def project, do: [app: :app, version: "0.1.0", elixir: "~> 1.16"]\nend\n',  # noqa: E501
        "lib/app.ex": "defmodule App do\n  def hello, do: :ok\nend\n",
    }


def _sc_haskell(s: str) -> dict[str, str]:
    return {
        "app/Main.hs": 'module Main where\n\nmain :: IO ()\nmain = putStrLn "status: ok"\n',
        "app.cabal": "cabal-version: 2.4\nname: app\nversion: 0.1.0\n\nexecutable app\n  main-is: Main.hs\n  hs-source-dirs: app\n  build-depends: base\n  default-language: Haskell2010\n",  # noqa: E501
    }


def _sc_perl(s: str) -> dict[str, str]:
    note = _first_line(s)
    return {
        "app.pl": f'#!/usr/bin/perl\nuse strict;\nuse warnings;\n\n# {note}\nprint "status: ok\\n";\n'  # noqa: E501
    }  # noqa: E501


def _sc_r(s: str) -> dict[str, str]:
    note = _first_line(s)
    return {"app.R": f'# {note}\nmain <- function() cat("status: ok\\n")\nmain()\n'}


def _sc_sql(s: str) -> dict[str, str]:
    note = _first_line(s)
    return {
        "schema.sql": f"-- {note}\nCREATE TABLE items (\n    id INTEGER PRIMARY KEY,\n    name TEXT NOT NULL\n);\n\nSELECT * FROM items;\n"  # noqa: E501
    }  # noqa: E501


def _sc_terraform(s: str) -> dict[str, str]:
    return {
        "main.tf": 'terraform {\n  required_version = ">= 1.5"\n}\n\nvariable "name" {\n  type    = string\n  default = "app"\n}\n\noutput "status" {\n  value = "ok"\n}\n',  # noqa: E501
    }


def _sc_bicep(s: str) -> dict[str, str]:
    return {
        "main.bicep": "param location string = resourceGroup().location\nparam name string = 'app'\noutput status string = 'ok'\n",  # noqa: E501
    }


def _sc_zig(s: str) -> dict[str, str]:
    return {
        "main.zig": 'const std = @import("std");\npub fn main() void {\n    std.debug.print("status: ok\n", .{});\n}\n',  # noqa: E501
        "build.zig": 'const std = @import("std");\npub fn build(b: *std.Build) void {\n    _ = b;\n}\n',  # noqa: E501
    }


def _sc_nim(s: str) -> dict[str, str]:
    note = _first_line(s)
    return {
        "main.nim": f'# {note}\necho "status: ok"\n',
        "app.nimble": 'version = "0.1.0"\nauthor = "app"\ndescription = "app"\nlicense = "MIT"\nsrcDir = "."\nbin = @["main"]\n',  # noqa: E501
    }


def _sc_clojure(s: str) -> dict[str, str]:
    return {
        "src/app/core.clj": '(ns app.core)\n\n(defn -main [& _args]\n  (println "status: ok"))\n',
        "deps.edn": '{:paths ["src"]}\n',
    }


def _sc_fsharp(s: str) -> dict[str, str]:
    return {
        "Program.fs": 'printfn "status: ok"\n',
        "app.fsproj": '<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>Exe</OutputType><TargetFramework>net8.0</TargetFramework></PropertyGroup><ItemGroup><Compile Include="Program.fs" /></ItemGroup></Project>\n',  # noqa: E501
    }


def _sc_dart_server(s: str) -> dict[str, str]:
    return {
        "bin/server.dart": 'import "dart:io";\n\nFuture<void> main() async {\n  final server = await HttpServer.bind(InternetAddress.anyIPv4, 8000);\n  await for (final req in server) {\n    req.response..write("status: ok")..close();\n  }\n}\n',  # noqa: E501
        "pubspec.yaml": "name: server\nenvironment:\n  sdk: '>=3.0.0 <4.0.0'\n",
    }


def _sc_graphql(s: str) -> dict[str, str]:
    note = _first_line(s)
    return {
        "schema.graphql": f"# {note}\ntype Query {{\n  status: String!\n  items: [Item!]!\n}}\n\ntype Item {{\n  id: ID!\n  name: String!\n}}\n",  # noqa: E501
    }


def _sc_dockerfile(s: str) -> dict[str, str]:
    note = _first_line(s)
    return {
        "Dockerfile": f'# {note}\nFROM alpine:3.19\nWORKDIR /app\nCOPY . .\nCMD ["echo", "status: ok"]\n',  # noqa: E501
        ".dockerignore": ".git\nnode_modules\n",
    }


def _sc_ansible(s: str) -> dict[str, str]:
    note = _first_line(s)
    return {
        "playbook.yml": f'---\n# {note}\n- hosts: all\n  tasks:\n    - name: report status\n      ansible.builtin.debug:\n        msg: "ok"\n',  # noqa: E501
        "inventory.ini": "localhost ansible_connection=local\n",
    }


def _sc_elm(s: str) -> dict[str, str]:
    return {
        "src/Main.elm": 'module Main exposing (main)\n\nimport Html exposing (text)\n\nmain =\n    text "status: ok"\n',  # noqa: E501
        "elm.json": '{\n  "type": "application",\n  "source-directories": ["src"],\n  "elm-version": "0.19.1"\n}\n',  # noqa: E501
    }


def _sc_ocaml(s: str) -> dict[str, str]:
    return {
        "bin/main.ml": 'let () = print_endline "status: ok"\n',
        "dune-project": "(lang dune 3.0)\n",
        "bin/dune": "(executable\n (name main))\n",
    }


def _sc_julia(s: str) -> dict[str, str]:
    note = _first_line(s)
    return {
        "src/App.jl": f'module App\n\n# {note}\ngreet() = "status: ok"\n\nend\n',
        "Project.toml": 'name = "App"\nuuid = "00000000-0000-0000-0000-000000000000"\nversion = "0.1.0"\n',  # noqa: E501
    }


def _sc_solidity(s: str) -> dict[str, str]:
    return {
        "src/Contract.sol": '// SPDX-License-Identifier: MIT\npragma solidity ^0.8.20;\n\ncontract Status {\n    function status() external pure returns (string memory) {\n        return "ok";\n    }\n}\n',  # noqa: E501
        "foundry.toml": '[profile.default]\nsrc = "src"\ntest = "test"\n',
    }


def _sc_protobuf(s: str) -> dict[str, str]:
    note = _first_line(s)
    return {
        "proto/app.proto": f'syntax = "proto3";\n\npackage app;\n\n// {note}\nmessage Item {{\n  int32 id = 1;\n  string name = 2;\n}}\n\nservice AppService {{\n  rpc GetItem (ItemRequest) returns (Item);\n}}\n\nmessage ItemRequest {{ int32 id = 1; }}\n',  # noqa: E501
    }


def _sc_openapi(s: str) -> dict[str, str]:
    note = _first_line(s)
    return {
        "openapi.yaml": f'openapi: 3.0.3\ninfo:\n  title: {note}\n  version: 0.1.0\npaths:\n  /health:\n    get:\n      responses:\n        "200":\n          description: OK\n',  # noqa: E501
    }


def _sc_helm(s: str) -> dict[str, str]:
    return {
        "Chart.yaml": 'apiVersion: v2\nname: app\nversion: 0.1.0\nappVersion: "1.0.0"\n',
        "values.yaml": "replicaCount: 1\nimage:\n  repository: nginx\n  tag: latest\n",
        "templates/deployment.yaml": "apiVersion: apps/v1\nkind: Deployment\nmetadata:\n  name: {{ .Release.Name }}\nspec:\n  replicas: {{ .Values.replicaCount }}\n",  # noqa: E501
    }


_STACK_SCAFFOLDS: dict[str, typing.Callable[[str], dict[str, str]]] = {
    "static-html": lambda s: {"index.html": _html_scaffold("App", s, "website")},
    "react": _sc_react,
    "vue": _sc_vue,
    "svelte": _sc_svelte,
    "python-fastapi": _api_scaffold,
    "python-flask": _sc_flask,
    "node-express": _sc_express,
    "go-http": _sc_go,
    "java-spring": _sc_spring,
    "dotnet-minimal": _sc_dotnet,
    "ruby-sinatra": _sc_sinatra,
    "php": _sc_php,
    "rust-cli": _sc_rust,
    "flutter": _sc_flutter,
    "react-native": _sc_react_native,
    "angular": _sc_angular,
    "nextjs": _sc_nextjs,
    "nestjs": _sc_nestjs,
    "python-django": _sc_django,
    "kotlin-ktor": _sc_ktor,
    "php-laravel": _sc_laravel,
    "swiftui": _sc_swiftui,
    "data-python": _sc_data_python,
    "remix": _sc_remix,
    "sveltekit": _sc_sveltekit,
    "go-gin": _sc_gin,
    "rust-axum": _sc_axum,
    "python-fastapi-sqlmodel": _sc_fastapi_sqlmodel,
    "java-spring-jpa": _sc_spring_jpa,
    "shell": _sc_shell,
    "c": _sc_c,
    "cpp": _sc_cpp,
    "kotlin": _sc_kotlin,
    "scala": _sc_scala,
    "elixir": _sc_elixir,
    "haskell": _sc_haskell,
    "perl": _sc_perl,
    "r": _sc_r,
    "sql": _sc_sql,
    "terraform": _sc_terraform,
    "bicep": _sc_bicep,
    "zig": _sc_zig,
    "nim": _sc_nim,
    "clojure": _sc_clojure,
    "fsharp": _sc_fsharp,
    "dart-server": _sc_dart_server,
    "graphql": _sc_graphql,
    "dockerfile": _sc_dockerfile,
    "ansible": _sc_ansible,
    "elm": _sc_elm,
    "ocaml": _sc_ocaml,
    "julia": _sc_julia,
    "solidity": _sc_solidity,
    "protobuf": _sc_protobuf,
    "openapi": _sc_openapi,
    "helm": _sc_helm,
}

# Grouped catalogue for the API / UI.
TECH_STACKS: list[dict[str, object]] = [
    {
        "category": "Web frontend",
        "stacks": [
            {"id": "static-html", "label": "HTML / CSS / JS"},
            {"id": "react", "label": "React"},
            {"id": "vue", "label": "Vue"},
            {"id": "svelte", "label": "Svelte"},
            {"id": "angular", "label": "Angular"},
            {"id": "nextjs", "label": "Next.js"},
            {"id": "remix", "label": "Remix"},
            {"id": "sveltekit", "label": "SvelteKit"},
            {"id": "elm", "label": "Elm"},
        ],
    },
    {
        "category": "Backend / API",
        "stacks": [
            {"id": "python-fastapi", "label": "Python · FastAPI"},
            {"id": "python-flask", "label": "Python · Flask"},
            {"id": "node-express", "label": "Node · Express"},
            {"id": "go-http", "label": "Go"},
            {"id": "java-spring", "label": "Java · Spring Boot"},
            {"id": "dotnet-minimal", "label": ".NET · Minimal API"},
            {"id": "ruby-sinatra", "label": "Ruby · Sinatra"},
            {"id": "php", "label": "PHP"},
            {"id": "nestjs", "label": "Node · NestJS"},
            {"id": "python-django", "label": "Python · Django"},
            {"id": "kotlin-ktor", "label": "Kotlin · Ktor"},
            {"id": "php-laravel", "label": "PHP · Laravel"},
            {"id": "go-gin", "label": "Go · Gin"},
            {"id": "rust-axum", "label": "Rust · Axum"},
            {"id": "python-fastapi-sqlmodel", "label": "Python · FastAPI + SQLModel"},
            {"id": "java-spring-jpa", "label": "Java · Spring + JPA"},
            {"id": "kotlin", "label": "Kotlin"},
            {"id": "scala", "label": "Scala"},
            {"id": "elixir", "label": "Elixir"},
            {"id": "haskell", "label": "Haskell"},
            {"id": "clojure", "label": "Clojure"},
            {"id": "fsharp", "label": "F#"},
            {"id": "dart-server", "label": "Dart (server)"},
            {"id": "graphql", "label": "GraphQL schema"},
            {"id": "solidity", "label": "Solidity"},
            {"id": "protobuf", "label": "Protobuf / gRPC"},
            {"id": "openapi", "label": "OpenAPI spec"},
        ],
    },
    {
        "category": "Mobile",
        "stacks": [
            {"id": "flutter", "label": "Flutter"},
            {"id": "react-native", "label": "React Native"},
            {"id": "swiftui", "label": "iOS · SwiftUI"},
        ],
    },
    {
        "category": "Systems / CLI",
        "stacks": [
            {"id": "rust-cli", "label": "Rust"},
            {"id": "c", "label": "C"},
            {"id": "cpp", "label": "C++"},
            {"id": "shell", "label": "Shell / Bash"},
            {"id": "perl", "label": "Perl"},
            {"id": "zig", "label": "Zig"},
            {"id": "nim", "label": "Nim"},
            {"id": "ocaml", "label": "OCaml"},
        ],
    },
    {
        "category": "Data / ML",
        "stacks": [
            {"id": "data-python", "label": "Python · pandas / scikit-learn"},
            {"id": "julia", "label": "Julia"},
            {"id": "r", "label": "R"},
            {"id": "sql", "label": "SQL"},
        ],
    },
    {
        "category": "Infrastructure",
        "stacks": [
            {"id": "terraform", "label": "Terraform"},
            {"id": "bicep", "label": "Bicep"},
            {"id": "dockerfile", "label": "Dockerfile"},
            {"id": "ansible", "label": "Ansible"},
            {"id": "helm", "label": "Helm chart"},
        ],
    },
]


_STACK_FRAMEWORK: dict[str, str] = {
    "python-fastapi": "pytest",
    "python-flask": "pytest",
    "python-django": "pytest",
    "data-python": "pytest",
    "python-fastapi-sqlmodel": "pytest",
    "react": "jest",
    "vue": "jest",
    "svelte": "jest",
    "node-express": "jest",
    "nestjs": "jest",
    "react-native": "jest",
    "angular": "jest",
    "nextjs": "jest",
    "remix": "jest",
    "sveltekit": "jest",
    "static-html": "jest",
    "go-http": "gotest",
    "go-gin": "gotest",
    "java-spring": "junit",
    "java-spring-jpa": "junit",
    "kotlin-ktor": "junit",
    "rust-cli": "cargotest",
    "rust-axum": "cargotest",
    "dotnet-minimal": "dotnettest",
    "php": "phpunit",
    "php-laravel": "phpunit",
    "flutter": "fluttertest",
    "swiftui": "xctest",
    "shell": "shelltest",
    "c": "ctest",
    "cpp": "cpptest",
    "kotlin": "kotlintest",
    "scala": "scalatest",
    "elixir": "exunit",
    "haskell": "hspec",
    "perl": "perltest",
    "r": "testthat",
    "zig": "zigtest",
    "nim": "nimtest",
    "clojure": "clojuretest",
    "fsharp": "fsharptest",
    "dart-server": "darttest",
    "elm": "elmtest",
    "ocaml": "ocamltest",
    "julia": "juliatest",
    "solidity": "soliditytest",
}

_TEST_FILES: dict[str, dict[str, str]] = {
    "pytest": {"tests/test_smoke.py": "def test_smoke() -> None:\n    assert 1 + 1 == 2\n"},
    "jest": {"app.test.js": 'test("smoke", () => {\n  expect(1 + 1).toBe(2);\n});\n'},
    "gotest": {
        "main_test.go": 'package main\n\nimport "testing"\n\nfunc TestSmoke(t *testing.T) {\n\tif 1+1 != 2 {\n\t\tt.Fatal("math is broken")\n\t}\n}\n'  # noqa: E501
    },  # noqa: E501
    "junit": {
        "src/test/java/com/app/SmokeTest.java": "package com.app;\nimport org.junit.jupiter.api.*;\n\nclass SmokeTest {\n    @Test\n    void smoke() { Assertions.assertEquals(2, 1 + 1); }\n}\n"  # noqa: E501
    },  # noqa: E501
    "cargotest": {"tests/smoke.rs": "#[test]\nfn smoke() {\n    assert_eq!(2, 1 + 1);\n}\n"},
    "dotnettest": {
        "AppTests.cs": "using Xunit;\n\npublic class AppTests {\n    [Fact]\n    public void Smoke() { Assert.Equal(2, 1 + 1); }\n}\n"  # noqa: E501
    },  # noqa: E501
    "phpunit": {
        "tests/SmokeTest.php": "<?php\nuse PHPUnit\\Framework\\TestCase;\n\nclass SmokeTest extends TestCase {\n    public function testSmoke(): void { $this->assertSame(2, 1 + 1); }\n}\n"  # noqa: E501
    },  # noqa: E501
    "fluttertest": {
        "test/widget_test.dart": "import 'package:flutter_test/flutter_test.dart';\n\nvoid main() {\n  test('smoke', () { expect(1 + 1, 2); });\n}\n"  # noqa: E501
    },  # noqa: E501
    "xctest": {
        "AppTests.swift": "import XCTest\n\nfinal class AppTests: XCTestCase {\n    func testSmoke() { XCTAssertEqual(2, 1 + 1) }\n}\n"  # noqa: E501
    },  # noqa: E501
    "shelltest": {"test.sh": '#!/usr/bin/env bash\nset -e\n[ "$((1 + 1))" -eq 2 ] && echo ok\n'},
    "ctest": {
        "test.c": "#include <assert.h>\n\nint main(void) {\n    assert(1 + 1 == 2);\n    return 0;\n}\n"  # noqa: E501
    },
    "cpptest": {
        "test.cpp": "#include <cassert>\n\nint main() {\n    assert(1 + 1 == 2);\n    return 0;\n}\n"  # noqa: E501
    },
    "kotlintest": {
        "src/test/kotlin/SmokeTest.kt": "import kotlin.test.Test\nimport kotlin.test.assertEquals\n\nclass SmokeTest {\n    @Test fun smoke() { assertEquals(2, 1 + 1) }\n}\n"  # noqa: E501
    },  # noqa: E501
    "scalatest": {
        "src/test/scala/SmokeSuite.scala": 'class SmokeSuite extends munit.FunSuite {\n  test("smoke") { assertEquals(2, 1 + 1) }\n}\n'  # noqa: E501
    },  # noqa: E501
    "exunit": {
        "test/app_test.exs": 'defmodule AppTest do\n  use ExUnit.Case\n  test "smoke" do\n    assert 1 + 1 == 2\n  end\nend\n'  # noqa: E501
    },  # noqa: E501
    "hspec": {
        "test/Spec.hs": 'main :: IO ()\nmain = if 1 + 1 == 2 then putStrLn "ok" else error "fail"\n'
    },  # noqa: E501
    "perltest": {
        "t/smoke.t": 'use strict;\nuse warnings;\nuse Test::More tests => 1;\nis(1 + 1, 2, "smoke");\n'  # noqa: E501
    },  # noqa: E501
    "testthat": {"tests/testthat/test-smoke.R": 'test_that("smoke", { expect_equal(1 + 1, 2) })\n'},  # noqa: E501
    "zigtest": {
        "test.zig": 'const std = @import("std");\ntest "smoke" {\n    try std.testing.expectEqual(2, 1 + 1);\n}\n'  # noqa: E501
    },  # noqa: E501
    "nimtest": {"tests/test_smoke.nim": 'import unittest\n\ntest "smoke":\n  check 1 + 1 == 2\n'},
    "clojuretest": {
        "test/app/core_test.clj": "(ns app.core-test (:require [clojure.test :refer :all]))\n\n(deftest smoke (is (= 2 (+ 1 1))))\n"  # noqa: E501
    },  # noqa: E501
    "fsharptest": {
        "Tests.fs": "module Tests\nopen Xunit\n\n[<Fact>]\nlet smoke () = Assert.Equal(2, 1 + 1)\n"
    },  # noqa: E501
    "darttest": {
        "test/server_test.dart": 'import "package:test/test.dart";\n\nvoid main() {\n  test("smoke", () { expect(1 + 1, 2); });\n}\n'  # noqa: E501
    },  # noqa: E501
    "elmtest": {
        "tests/Tests.elm": 'module Tests exposing (..)\n\nimport Expect\nimport Test exposing (..)\n\nsmoke : Test\nsmoke = test "smoke" (\\_ -> Expect.equal 2 (1 + 1))\n'  # noqa: E501
    },  # noqa: E501
    "ocamltest": {"test/test_smoke.ml": "let () = assert (1 + 1 = 2)\n"},
    "juliatest": {"test/runtests.jl": "using Test\n\n@test 1 + 1 == 2\n"},
    "soliditytest": {
        "test/Contract.t.sol": '// SPDX-License-Identifier: MIT\npragma solidity ^0.8.20;\nimport "forge-std/Test.sol";\n\ncontract SmokeTest is Test {\n    function testSmoke() public pure { assertEq(2, 1 + 1); }\n}\n'  # noqa: E501
    },  # noqa: E501
}


def scaffold_for_stack(spec: str, tech_stack: str) -> GeneratedArtifact | None:
    """Return a scaffold (plus a starter test) for a known tech stack, or None."""
    builder = _STACK_SCAFFOLDS.get(tech_stack)
    if builder is None:
        return None
    files = builder(spec)
    framework = _STACK_FRAMEWORK.get(tech_stack)
    if framework and framework in _TEST_FILES:
        for path, content in _TEST_FILES[framework].items():
            files.setdefault(path, content)
    return GeneratedArtifact(
        provider="template",
        summary=f"Generated a {tech_stack} scaffold with a starter test ({', '.join(sorted(files))}).",  # noqa: E501
        files=files,
    )


# ---------------------------------------------------------------------------
# Stack detection — infer a tech stack from a repository's file list
# ---------------------------------------------------------------------------
# Ordered most-specific first; the first marker present wins.
_STACK_MARKERS: list[tuple[str, str]] = [
    ("angular.json", "angular"),
    ("next.config.js", "nextjs"),
    ("next.config.mjs", "nextjs"),
    ("next.config.ts", "nextjs"),
    ("remix.config.js", "remix"),
    ("remix.config.mjs", "remix"),
    ("svelte.config.js", "sveltekit"),
    ("nest-cli.json", "nestjs"),
    ("pubspec.yaml", "flutter"),
    ("manage.py", "python-django"),
    ("go.mod", "go-http"),
    ("Cargo.toml", "rust-cli"),
    ("composer.json", "php-laravel"),
    ("build.gradle.kts", "kotlin-ktor"),
    ("pom.xml", "java-spring"),
    ("build.gradle", "java-spring"),
    ("build.sbt", "scala"),
    ("mix.exs", "elixir"),
    ("build.zig", "zig"),
    ("deps.edn", "clojure"),
    ("elm.json", "elm"),
    ("dune-project", "ocaml"),
    ("Project.toml", "julia"),
    ("foundry.toml", "solidity"),
    ("Chart.yaml", "helm"),
    ("Package.swift", "swiftui"),
]


def detect_stack(filenames: list[str]) -> str | None:
    """Infer a tech-stack id from a repository's file list, or None if unknown.

    Uses marker/manifest files (``go.mod`` → Go, ``pom.xml`` → Spring, framework
    config files → that framework). Falls back to generic Node/Python when only a
    bare ``package.json`` / ``requirements.txt`` is present.
    """
    names = {f.rsplit("/", 1)[-1] for f in filenames}
    for marker, stack in _STACK_MARKERS:
        if marker in names:
            return stack
    if any(f.endswith(".csproj") for f in filenames):
        return "dotnet-minimal"
    if any(f.endswith(".xcodeproj") for f in filenames):
        return "swiftui"
    if "CMakeLists.txt" in names or any(f.endswith((".cpp", ".cc", ".cxx")) for f in filenames):
        return "cpp"
    if any(f.endswith(".c") for f in filenames):
        return "c"
    if any(f.endswith(".sh") for f in filenames):
        return "shell"
    if any(f.endswith(".cabal") for f in filenames):
        return "haskell"
    if any(f.endswith(".tf") for f in filenames):
        return "terraform"
    if any(f.endswith(".bicep") for f in filenames):
        return "bicep"
    if any(f.endswith(".nimble") for f in filenames):
        return "nim"
    if any(f.endswith(".fsproj") for f in filenames):
        return "fsharp"
    if any(f.endswith(".sol") for f in filenames):
        return "solidity"
    if "package.json" in names:
        return "node-express"
    if "requirements.txt" in names or "pyproject.toml" in names:
        return "python-fastapi"
    if "index.html" in names:
        return "static-html"
    if any(f.endswith(".graphql") for f in filenames):
        return "graphql"
    if "Dockerfile" in names:
        return "dockerfile"
    if "ansible.cfg" in names or "playbook.yml" in names:
        return "ansible"
    if any(f.endswith(".proto") for f in filenames):
        return "protobuf"
    if any(f in names for f in ("openapi.yaml", "openapi.yml", "openapi.json")):
        return "openapi"
    return None


def framework_for_stack(tech_stack: str | None) -> str | None:
    """Return the test framework mapped to a stack (e.g. ``pytest``), or None."""
    return _STACK_FRAMEWORK.get(tech_stack or "")


# ---------------------------------------------------------------------------
# Pipeline: the command a CI runner uses to run a stack's generated tests
# ---------------------------------------------------------------------------
_TEST_COMMANDS: dict[str, str] = {
    "pytest": "pytest -q",
    "jest": "npm test",
    "gotest": "go test ./...",
    "junit": "mvn -q test",
    "cargotest": "cargo test",
    "dotnettest": "dotnet test",
    "phpunit": "vendor/bin/phpunit",
    "fluttertest": "flutter test",
    "xctest": "swift test",
    "shelltest": "bash test.sh",
    "ctest": "cc -o /tmp/t test.c && /tmp/t",
    "cpptest": "c++ -o /tmp/t test.cpp && /tmp/t",
    "kotlintest": "gradle test",
    "scalatest": "sbt test",
    "exunit": "mix test",
    "hspec": "runghc test/Spec.hs",
    "perltest": "prove t/",
    "testthat": "Rscript -e 'testthat::test_dir(\"tests/testthat\")'",
    "zigtest": "zig test test.zig",
    "nimtest": "nim c -r tests/test_smoke.nim",
    "clojuretest": "clojure -M:test",
    "fsharptest": "dotnet test",
    "darttest": "dart test",
    "elmtest": "npx elm-test",
    "ocamltest": "dune test",
    "juliatest": "julia test/runtests.jl",
    "soliditytest": "forge test",
}


def test_command_for(framework: str | None) -> str | None:
    """Return the shell command a CI runner uses to run a framework's tests."""
    return _TEST_COMMANDS.get(framework or "")
