"""sprint management schema

Revision ID: 0f69215c4b24
Revises: ef6032c1d000
Create Date: 2026-07-29 03:15:46.280391
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

revision: str = "0f69215c4b24"
down_revision: str | None = "ef6032c1d000"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sprints",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("goal", sa.String(length=1000), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "planned",
                "active",
                "completed",
                "cancelled",
                name="sprintstatus",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("capacity_hours", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column(
            "created_date",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("modified_by", sa.Uuid(), nullable=True),
        sa.Column("modified_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "number", name="uq_sprint_number"),
    )
    op.create_index(op.f("ix_sprints_is_deleted"), "sprints", ["is_deleted"], unique=False)
    op.create_index(
        op.f("ix_sprints_organization_id"), "sprints", ["organization_id"], unique=False
    )
    op.create_index(op.f("ix_sprints_project_id"), "sprints", ["project_id"], unique=False)
    op.create_index(op.f("ix_sprints_status"), "sprints", ["status"], unique=False)
    # Alembic emits a separate ADD CONSTRAINT for an inline foreign key, which
    # SQLite cannot ALTER in. On SQLite (dev/tests only) we add a plain column;
    # on PostgreSQL we add the column and a named foreign-key constraint.
    bind = op.get_bind()
    op.add_column("tasks", sa.Column("sprint_id", sa.Uuid(), nullable=True))
    op.create_index(op.f("ix_tasks_sprint_id"), "tasks", ["sprint_id"], unique=False)
    if bind.dialect.name != "sqlite":
        op.create_foreign_key(
            "fk_tasks_sprint_id_sprints",
            "tasks",
            "sprints",
            ["sprint_id"],
            ["id"],
            ondelete="SET NULL",
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    bind = op.get_bind()
    if bind.dialect.name != "sqlite":
        op.drop_constraint("fk_tasks_sprint_id_sprints", "tasks", type_="foreignkey")
    op.drop_index(op.f("ix_tasks_sprint_id"), table_name="tasks")
    op.drop_column("tasks", "sprint_id")
    op.drop_index(op.f("ix_sprints_status"), table_name="sprints")
    op.drop_index(op.f("ix_sprints_project_id"), table_name="sprints")
    op.drop_index(op.f("ix_sprints_organization_id"), table_name="sprints")
    op.drop_index(op.f("ix_sprints_is_deleted"), table_name="sprints")
    op.drop_table("sprints")
