"""add sso_configurations table

Revision ID: 1449c0bee584
Revises: 465f0ed36271
Create Date: 2026-09-19 12:58:32.086058
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

revision: str = "1449c0bee584"
down_revision: str | None = "465f0ed36271"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sso_configurations",
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("client_id", sa.String(length=500), nullable=False),
        sa.Column("client_secret", sa.String(length=1000), nullable=False),
        sa.Column("issuer", sa.String(length=1000), nullable=False),
        sa.Column("authorize_url", sa.String(length=1000), nullable=False),
        sa.Column("token_url", sa.String(length=1000), nullable=False),
        sa.Column("jwks_url", sa.String(length=1000), nullable=False),
        sa.Column("default_role_name", sa.String(length=200), nullable=False),
        sa.Column("allowed_domains", sa.JSON(), nullable=False),
        sa.Column("is_enabled", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column(
            "created_date",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("modified_by", sa.Uuid(), nullable=True),
        sa.Column("modified_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_sso_configurations_is_deleted"),
        "sso_configurations",
        ["is_deleted"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sso_configurations_is_enabled"),
        "sso_configurations",
        ["is_enabled"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sso_configurations_organization_id"),
        "sso_configurations",
        ["organization_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_sso_configurations_organization_id"), table_name="sso_configurations")
    op.drop_index(op.f("ix_sso_configurations_is_enabled"), table_name="sso_configurations")
    op.drop_index(op.f("ix_sso_configurations_is_deleted"), table_name="sso_configurations")
    op.drop_table("sso_configurations")
    # ### end Alembic commands ###
