"""dashboard schema

Revision ID: 15addb18d376
Revises: 3b47b86df73c
Create Date: 2026-07-30 02:42:00.873437
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '15addb18d376'
down_revision: str | None = '3b47b86df73c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dashboards',
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=False),
    sa.Column('is_shared', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('layout', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('modified_by', sa.Uuid(), nullable=True),
    sa.Column('modified_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dashboards_is_default'), 'dashboards', ['is_default'], unique=False)
    op.create_index(op.f('ix_dashboards_is_deleted'), 'dashboards', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_dashboards_is_shared'), 'dashboards', ['is_shared'], unique=False)
    op.create_index(op.f('ix_dashboards_organization_id'), 'dashboards', ['organization_id'], unique=False)
    op.create_table('dashboard_widgets',
    sa.Column('dashboard_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('widget_type', sa.Enum('report', 'text', name='widgettype', native_enum=False, length=20), nullable=False),
    sa.Column('report_type', sa.Enum('project_status', 'raid_summary', 'timesheet_hours', 'milestone_status', 'financial_summary', 'portfolio_overview', name='reporttype', native_enum=False, length=20), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('content', sa.String(length=8000), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('modified_by', sa.Uuid(), nullable=True),
    sa.Column('modified_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['dashboard_id'], ['dashboards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dashboard_widgets_dashboard_id'), 'dashboard_widgets', ['dashboard_id'], unique=False)
    op.create_index(op.f('ix_dashboard_widgets_is_deleted'), 'dashboard_widgets', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_dashboard_widgets_organization_id'), 'dashboard_widgets', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dashboard_widgets_organization_id'), table_name='dashboard_widgets')
    op.drop_index(op.f('ix_dashboard_widgets_is_deleted'), table_name='dashboard_widgets')
    op.drop_index(op.f('ix_dashboard_widgets_dashboard_id'), table_name='dashboard_widgets')
    op.drop_table('dashboard_widgets')
    op.drop_index(op.f('ix_dashboards_organization_id'), table_name='dashboards')
    op.drop_index(op.f('ix_dashboards_is_shared'), table_name='dashboards')
    op.drop_index(op.f('ix_dashboards_is_deleted'), table_name='dashboards')
    op.drop_index(op.f('ix_dashboards_is_default'), table_name='dashboards')
    op.drop_table('dashboards')
    # ### end Alembic commands ###
