"""add skills and resource_skills tables

Revision ID: 189ee006bb0a
Revises: e80fb33685b1
Create Date: 2026-08-01 07:37:29.931238
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

revision: str = "189ee006bb0a"
down_revision: str | None = "e80fb33685b1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "skills",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "technical",
                "functional",
                "domain",
                "leadership",
                "other",
                name="skillcategory",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("description", sa.String(length=2000), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column(
            "created_date",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("modified_by", sa.Uuid(), nullable=True),
        sa.Column("modified_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_skills_category"), "skills", ["category"], unique=False)
    op.create_index(op.f("ix_skills_is_deleted"), "skills", ["is_deleted"], unique=False)
    op.create_index(op.f("ix_skills_name"), "skills", ["name"], unique=False)
    op.create_index(op.f("ix_skills_organization_id"), "skills", ["organization_id"], unique=False)
    op.create_table(
        "resource_skills",
        sa.Column("resource_id", sa.Uuid(), nullable=False),
        sa.Column("skill_id", sa.Uuid(), nullable=False),
        sa.Column("proficiency", sa.Integer(), nullable=False),
        sa.Column("years_experience", sa.Numeric(precision=4, scale=1), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column(
            "created_date",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("modified_by", sa.Uuid(), nullable=True),
        sa.Column("modified_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["resource_id"], ["resources.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["skill_id"], ["skills.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_resource_skills_is_deleted"),
        "resource_skills",
        ["is_deleted"],
        unique=False,
    )
    op.create_index(
        op.f("ix_resource_skills_organization_id"),
        "resource_skills",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_resource_skills_resource_id"),
        "resource_skills",
        ["resource_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_resource_skills_skill_id"),
        "resource_skills",
        ["skill_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_resource_skills_skill_id"), table_name="resource_skills")
    op.drop_index(op.f("ix_resource_skills_resource_id"), table_name="resource_skills")
    op.drop_index(op.f("ix_resource_skills_organization_id"), table_name="resource_skills")
    op.drop_index(op.f("ix_resource_skills_is_deleted"), table_name="resource_skills")
    op.drop_table("resource_skills")
    op.drop_index(op.f("ix_skills_organization_id"), table_name="skills")
    op.drop_index(op.f("ix_skills_name"), table_name="skills")
    op.drop_index(op.f("ix_skills_is_deleted"), table_name="skills")
    op.drop_index(op.f("ix_skills_category"), table_name="skills")
    op.drop_table("skills")
    # ### end Alembic commands ###
