"""add build_requests and pipeline_runs

Revision ID: 2406e9f2061c
Revises: 78aea5410b66
Create Date: 2026-09-14 10:35:51.784807
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '2406e9f2061c'
down_revision: str | None = '78aea5410b66'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('build_requests',
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('target_type', sa.Enum('web_app', 'website', 'mobile_app', 'api_service', 'other', name='buildtargettype', native_enum=False, length=20), nullable=False),
    sa.Column('spec', sa.String(length=8000), nullable=False),
    sa.Column('repository_url', sa.String(length=1000), nullable=False),
    sa.Column('status', sa.Enum('requested', 'generating', 'generated', 'testing', 'tested', 'deploying', 'deployed', 'failed', 'cancelled', name='buildstatus', native_enum=False, length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('modified_by', sa.Uuid(), nullable=True),
    sa.Column('modified_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_build_requests_is_deleted'), 'build_requests', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_build_requests_organization_id'), 'build_requests', ['organization_id'], unique=False)
    op.create_index(op.f('ix_build_requests_project_id'), 'build_requests', ['project_id'], unique=False)
    op.create_index(op.f('ix_build_requests_status'), 'build_requests', ['status'], unique=False)
    op.create_index(op.f('ix_build_requests_target_type'), 'build_requests', ['target_type'], unique=False)
    op.create_table('pipeline_runs',
    sa.Column('build_request_id', sa.Uuid(), nullable=False),
    sa.Column('stage', sa.Enum('generate', 'test', 'deploy', name='pipelinestage', native_enum=False, length=20), nullable=False),
    sa.Column('status', sa.Enum('running', 'passed', 'failed', name='runstatus', native_enum=False, length=20), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('external_ref', sa.String(length=300), nullable=False),
    sa.Column('logs_url', sa.String(length=1000), nullable=False),
    sa.Column('message', sa.String(length=2000), nullable=False),
    sa.Column('started_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('modified_by', sa.Uuid(), nullable=True),
    sa.Column('modified_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['build_request_id'], ['build_requests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_runs_build_request_id'), 'pipeline_runs', ['build_request_id'], unique=False)
    op.create_index(op.f('ix_pipeline_runs_is_deleted'), 'pipeline_runs', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_pipeline_runs_organization_id'), 'pipeline_runs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_pipeline_runs_stage'), 'pipeline_runs', ['stage'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pipeline_runs_stage'), table_name='pipeline_runs')
    op.drop_index(op.f('ix_pipeline_runs_organization_id'), table_name='pipeline_runs')
    op.drop_index(op.f('ix_pipeline_runs_is_deleted'), table_name='pipeline_runs')
    op.drop_index(op.f('ix_pipeline_runs_build_request_id'), table_name='pipeline_runs')
    op.drop_table('pipeline_runs')
    op.drop_index(op.f('ix_build_requests_target_type'), table_name='build_requests')
    op.drop_index(op.f('ix_build_requests_status'), table_name='build_requests')
    op.drop_index(op.f('ix_build_requests_project_id'), table_name='build_requests')
    op.drop_index(op.f('ix_build_requests_organization_id'), table_name='build_requests')
    op.drop_index(op.f('ix_build_requests_is_deleted'), table_name='build_requests')
    op.drop_table('build_requests')
    # ### end Alembic commands ###
