"""add metric_snapshots table

Revision ID: 252b656da890
Revises: e369f1f121e9
Create Date: 2026-09-26 10:02:07.598407
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '252b656da890'
down_revision: str | None = 'e369f1f121e9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metric_snapshots',
    sa.Column('scope', sa.String(length=20), nullable=False),
    sa.Column('scope_id', sa.Uuid(), nullable=True),
    sa.Column('metric', sa.String(length=40), nullable=False),
    sa.Column('value', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('captured_date', sa.Date(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('modified_by', sa.Uuid(), nullable=True),
    sa.Column('modified_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'scope', 'scope_id', 'metric', 'captured_date', name='uq_metric_snapshot')
    )
    op.create_index(op.f('ix_metric_snapshots_captured_date'), 'metric_snapshots', ['captured_date'], unique=False)
    op.create_index(op.f('ix_metric_snapshots_is_deleted'), 'metric_snapshots', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_metric_snapshots_metric'), 'metric_snapshots', ['metric'], unique=False)
    op.create_index(op.f('ix_metric_snapshots_organization_id'), 'metric_snapshots', ['organization_id'], unique=False)
    op.create_index(op.f('ix_metric_snapshots_scope'), 'metric_snapshots', ['scope'], unique=False)
    op.create_index(op.f('ix_metric_snapshots_scope_id'), 'metric_snapshots', ['scope_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_metric_snapshots_scope_id'), table_name='metric_snapshots')
    op.drop_index(op.f('ix_metric_snapshots_scope'), table_name='metric_snapshots')
    op.drop_index(op.f('ix_metric_snapshots_organization_id'), table_name='metric_snapshots')
    op.drop_index(op.f('ix_metric_snapshots_metric'), table_name='metric_snapshots')
    op.drop_index(op.f('ix_metric_snapshots_is_deleted'), table_name='metric_snapshots')
    op.drop_index(op.f('ix_metric_snapshots_captured_date'), table_name='metric_snapshots')
    op.drop_table('metric_snapshots')
    # ### end Alembic commands ###
