"""add vendor procurement tables

Revision ID: 2ec94f9166c9
Revises: b9d06ab258c5
Create Date: 2026-08-02 03:59:52.833316
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

revision: str = "2ec94f9166c9"
down_revision: str | None = "b9d06ab258c5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "vendors",
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "technology",
                "prof_services",
                "staffing",
                "hardware",
                "facilities",
                "other",
                name="vendorcategory",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "active",
                "inactive",
                "suspended",
                "blacklisted",
                name="vendorstatus",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("contact_name", sa.String(length=200), nullable=False),
        sa.Column("contact_email", sa.String(length=320), nullable=False),
        sa.Column("description", sa.String(length=4000), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column(
            "created_date",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("modified_by", sa.Uuid(), nullable=True),
        sa.Column("modified_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_vendors_category"), "vendors", ["category"], unique=False)
    op.create_index(op.f("ix_vendors_code"), "vendors", ["code"], unique=False)
    op.create_index(op.f("ix_vendors_is_deleted"), "vendors", ["is_deleted"], unique=False)
    op.create_index(op.f("ix_vendors_name"), "vendors", ["name"], unique=False)
    op.create_index(
        op.f("ix_vendors_organization_id"), "vendors", ["organization_id"], unique=False
    )
    op.create_index(op.f("ix_vendors_status"), "vendors", ["status"], unique=False)
    op.create_table(
        "contracts",
        sa.Column("vendor_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=True),
        sa.Column("owner_user_id", sa.Uuid(), nullable=True),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("reference", sa.String(length=100), nullable=False),
        sa.Column(
            "contract_type",
            sa.Enum(
                "fixed_price",
                "time_and_materials",
                "retainer",
                "subscription",
                "other",
                name="contracttype",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "active",
                "expired",
                "terminated",
                "completed",
                name="contractstatus",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("value", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column(
            "created_date",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("modified_by", sa.Uuid(), nullable=True),
        sa.Column("modified_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["owner_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["vendor_id"], ["vendors.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_contracts_contract_type"), "contracts", ["contract_type"], unique=False
    )
    op.create_index(op.f("ix_contracts_is_deleted"), "contracts", ["is_deleted"], unique=False)
    op.create_index(
        op.f("ix_contracts_organization_id"),
        "contracts",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_contracts_owner_user_id"), "contracts", ["owner_user_id"], unique=False
    )
    op.create_index(op.f("ix_contracts_project_id"), "contracts", ["project_id"], unique=False)
    op.create_index(op.f("ix_contracts_status"), "contracts", ["status"], unique=False)
    op.create_index(op.f("ix_contracts_vendor_id"), "contracts", ["vendor_id"], unique=False)
    op.create_table(
        "purchase_orders",
        sa.Column("vendor_id", sa.Uuid(), nullable=False),
        sa.Column("contract_id", sa.Uuid(), nullable=True),
        sa.Column("project_id", sa.Uuid(), nullable=True),
        sa.Column("reference", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=2000), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "issued",
                "partially_invoiced",
                "invoiced",
                "paid",
                "cancelled",
                name="purchaseorderstatus",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("committed_amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("invoiced_amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("order_date", sa.Date(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column(
            "created_date",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("modified_by", sa.Uuid(), nullable=True),
        sa.Column("modified_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["contract_id"], ["contracts.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["vendor_id"], ["vendors.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_purchase_orders_contract_id"),
        "purchase_orders",
        ["contract_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_purchase_orders_is_deleted"),
        "purchase_orders",
        ["is_deleted"],
        unique=False,
    )
    op.create_index(
        op.f("ix_purchase_orders_organization_id"),
        "purchase_orders",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_purchase_orders_project_id"),
        "purchase_orders",
        ["project_id"],
        unique=False,
    )
    op.create_index(op.f("ix_purchase_orders_status"), "purchase_orders", ["status"], unique=False)
    op.create_index(
        op.f("ix_purchase_orders_vendor_id"),
        "purchase_orders",
        ["vendor_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_purchase_orders_vendor_id"), table_name="purchase_orders")
    op.drop_index(op.f("ix_purchase_orders_status"), table_name="purchase_orders")
    op.drop_index(op.f("ix_purchase_orders_project_id"), table_name="purchase_orders")
    op.drop_index(op.f("ix_purchase_orders_organization_id"), table_name="purchase_orders")
    op.drop_index(op.f("ix_purchase_orders_is_deleted"), table_name="purchase_orders")
    op.drop_index(op.f("ix_purchase_orders_contract_id"), table_name="purchase_orders")
    op.drop_table("purchase_orders")
    op.drop_index(op.f("ix_contracts_vendor_id"), table_name="contracts")
    op.drop_index(op.f("ix_contracts_status"), table_name="contracts")
    op.drop_index(op.f("ix_contracts_project_id"), table_name="contracts")
    op.drop_index(op.f("ix_contracts_owner_user_id"), table_name="contracts")
    op.drop_index(op.f("ix_contracts_organization_id"), table_name="contracts")
    op.drop_index(op.f("ix_contracts_is_deleted"), table_name="contracts")
    op.drop_index(op.f("ix_contracts_contract_type"), table_name="contracts")
    op.drop_table("contracts")
    op.drop_index(op.f("ix_vendors_status"), table_name="vendors")
    op.drop_index(op.f("ix_vendors_organization_id"), table_name="vendors")
    op.drop_index(op.f("ix_vendors_name"), table_name="vendors")
    op.drop_index(op.f("ix_vendors_is_deleted"), table_name="vendors")
    op.drop_index(op.f("ix_vendors_code"), table_name="vendors")
    op.drop_index(op.f("ix_vendors_category"), table_name="vendors")
    op.drop_table("vendors")
    # ### end Alembic commands ###
