"""report schema

Revision ID: 3b47b86df73c
Revises: 1944910debe3
Create Date: 2026-07-29 14:17:30.346554
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

revision: str = "3b47b86df73c"
down_revision: str | None = "1944910debe3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "report_definitions",
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("description", sa.String(length=2000), nullable=False),
        sa.Column(
            "report_type",
            sa.Enum(
                "project_status",
                "raid_summary",
                "timesheet_hours",
                "milestone_status",
                "financial_summary",
                "portfolio_overview",
                name="reporttype",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("parameters", sa.JSON(), nullable=False),
        sa.Column("is_shared", sa.Boolean(), nullable=False),
        sa.Column("last_run_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column(
            "created_date",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("modified_by", sa.Uuid(), nullable=True),
        sa.Column("modified_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_report_definitions_is_deleted"),
        "report_definitions",
        ["is_deleted"],
        unique=False,
    )
    op.create_index(
        op.f("ix_report_definitions_is_shared"),
        "report_definitions",
        ["is_shared"],
        unique=False,
    )
    op.create_index(
        op.f("ix_report_definitions_organization_id"),
        "report_definitions",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_report_definitions_report_type"),
        "report_definitions",
        ["report_type"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_report_definitions_report_type"), table_name="report_definitions")
    op.drop_index(op.f("ix_report_definitions_organization_id"), table_name="report_definitions")
    op.drop_index(op.f("ix_report_definitions_is_shared"), table_name="report_definitions")
    op.drop_index(op.f("ix_report_definitions_is_deleted"), table_name="report_definitions")
    op.drop_table("report_definitions")
    # ### end Alembic commands ###
