"""add jira connector tables

Revision ID: 462677b59290
Revises: 1449c0bee584
Create Date: 2026-09-21 02:53:45.804948
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '462677b59290'
down_revision: str | None = '1449c0bee584'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('external_links',
    sa.Column('system', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('external_key', sa.String(length=100), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=False),
    sa.Column('external_url', sa.String(length=500), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('modified_by', sa.Uuid(), nullable=True),
    sa.Column('modified_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'system', 'entity_type', 'entity_id', name='uq_external_link_entity')
    )
    op.create_index(op.f('ix_external_links_entity_id'), 'external_links', ['entity_id'], unique=False)
    op.create_index(op.f('ix_external_links_external_key'), 'external_links', ['external_key'], unique=False)
    op.create_index(op.f('ix_external_links_is_deleted'), 'external_links', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_external_links_organization_id'), 'external_links', ['organization_id'], unique=False)
    op.create_index(op.f('ix_external_links_system'), 'external_links', ['system'], unique=False)
    op.create_table('jira_connections',
    sa.Column('base_url', sa.String(length=500), nullable=False),
    sa.Column('project_key', sa.String(length=50), nullable=False),
    sa.Column('user_email', sa.String(length=320), nullable=False),
    sa.Column('api_token', sa.String(length=1000), nullable=False),
    sa.Column('webhook_secret', sa.String(length=200), nullable=False),
    sa.Column('default_project_id', sa.Uuid(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('modified_by', sa.Uuid(), nullable=True),
    sa.Column('modified_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['default_project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jira_connections_is_deleted'), 'jira_connections', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_jira_connections_is_enabled'), 'jira_connections', ['is_enabled'], unique=False)
    op.create_index(op.f('ix_jira_connections_organization_id'), 'jira_connections', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jira_connections_organization_id'), table_name='jira_connections')
    op.drop_index(op.f('ix_jira_connections_is_enabled'), table_name='jira_connections')
    op.drop_index(op.f('ix_jira_connections_is_deleted'), table_name='jira_connections')
    op.drop_table('jira_connections')
    op.drop_index(op.f('ix_external_links_system'), table_name='external_links')
    op.drop_index(op.f('ix_external_links_organization_id'), table_name='external_links')
    op.drop_index(op.f('ix_external_links_is_deleted'), table_name='external_links')
    op.drop_index(op.f('ix_external_links_external_key'), table_name='external_links')
    op.drop_index(op.f('ix_external_links_entity_id'), table_name='external_links')
    op.drop_table('external_links')
    # ### end Alembic commands ###
