"""add quality gate thresholds to build_requests

Revision ID: 465f0ed36271
Revises: 7eb23ea33168
Create Date: 2026-09-17 09:48:02.762010
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

revision: str = "465f0ed36271"
down_revision: str | None = "7eb23ea33168"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("build_requests", sa.Column("gate_min_coverage", sa.Integer(), nullable=True))
    op.add_column("build_requests", sa.Column("gate_max_p95_ms", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("build_requests", "gate_max_p95_ms")
    op.drop_column("build_requests", "gate_min_coverage")
    # ### end Alembic commands ###
