"""change request schema

Revision ID: 533548b7b94a
Revises: a3cc745f73da
Create Date: 2026-07-29 09:55:52.488177
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '533548b7b94a'
down_revision: str | None = 'a3cc745f73da'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('change_requests',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('requested_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('approver_user_id', sa.Uuid(), nullable=True),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.String(length=4000), nullable=False),
    sa.Column('reason', sa.String(length=4000), nullable=False),
    sa.Column('change_type', sa.Enum('scope', 'schedule', 'budget', 'resource', 'quality', 'other', name='changetype', native_enum=False, length=20), nullable=False),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', 'critical', name='changepriority', native_enum=False, length=20), nullable=False),
    sa.Column('status', sa.Enum('draft', 'submitted', 'under_review', 'approved', 'rejected', 'implemented', 'cancelled', name='changestatus', native_enum=False, length=20), nullable=False),
    sa.Column('schedule_impact_days', sa.Integer(), nullable=True),
    sa.Column('cost_impact', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('impact_summary', sa.String(length=4000), nullable=False),
    sa.Column('decision_notes', sa.String(length=4000), nullable=False),
    sa.Column('decided_date', sa.Date(), nullable=True),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('modified_by', sa.Uuid(), nullable=True),
    sa.Column('modified_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['approver_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'number', name='uq_change_number')
    )
    op.create_index(op.f('ix_change_requests_approver_user_id'), 'change_requests', ['approver_user_id'], unique=False)
    op.create_index(op.f('ix_change_requests_change_type'), 'change_requests', ['change_type'], unique=False)
    op.create_index(op.f('ix_change_requests_is_deleted'), 'change_requests', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_change_requests_organization_id'), 'change_requests', ['organization_id'], unique=False)
    op.create_index(op.f('ix_change_requests_project_id'), 'change_requests', ['project_id'], unique=False)
    op.create_index(op.f('ix_change_requests_status'), 'change_requests', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_change_requests_status'), table_name='change_requests')
    op.drop_index(op.f('ix_change_requests_project_id'), table_name='change_requests')
    op.drop_index(op.f('ix_change_requests_organization_id'), table_name='change_requests')
    op.drop_index(op.f('ix_change_requests_is_deleted'), table_name='change_requests')
    op.drop_index(op.f('ix_change_requests_change_type'), table_name='change_requests')
    op.drop_index(op.f('ix_change_requests_approver_user_id'), table_name='change_requests')
    op.drop_table('change_requests')
    # ### end Alembic commands ###
