"""milestone schema

Revision ID: 5b9b89fa940d
Revises: c20536e0a75b
Create Date: 2026-07-29 10:33:09.059110
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

revision: str = "5b9b89fa940d"
down_revision: str | None = "c20536e0a75b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "milestones",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("task_id", sa.Uuid(), nullable=True),
        sa.Column("owner_user_id", sa.Uuid(), nullable=True),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("description", sa.String(length=4000), nullable=False),
        sa.Column(
            "milestone_type",
            sa.Enum(
                "checkpoint",
                "deliverable",
                "phase_gate",
                "go_live",
                "external",
                "other",
                name="milestonetype",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "planned",
                "in_progress",
                "achieved",
                "missed",
                "cancelled",
                name="milestonestatus",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("target_date", sa.Date(), nullable=False),
        sa.Column("actual_date", sa.Date(), nullable=True),
        sa.Column("is_key", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column(
            "created_date",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("modified_by", sa.Uuid(), nullable=True),
        sa.Column("modified_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["owner_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "number", name="uq_milestone_number"),
    )
    op.create_index(op.f("ix_milestones_is_deleted"), "milestones", ["is_deleted"], unique=False)
    op.create_index(op.f("ix_milestones_is_key"), "milestones", ["is_key"], unique=False)
    op.create_index(
        op.f("ix_milestones_milestone_type"),
        "milestones",
        ["milestone_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_milestones_organization_id"),
        "milestones",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_milestones_owner_user_id"),
        "milestones",
        ["owner_user_id"],
        unique=False,
    )
    op.create_index(op.f("ix_milestones_project_id"), "milestones", ["project_id"], unique=False)
    op.create_index(op.f("ix_milestones_status"), "milestones", ["status"], unique=False)
    op.create_index(op.f("ix_milestones_task_id"), "milestones", ["task_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_milestones_task_id"), table_name="milestones")
    op.drop_index(op.f("ix_milestones_status"), table_name="milestones")
    op.drop_index(op.f("ix_milestones_project_id"), table_name="milestones")
    op.drop_index(op.f("ix_milestones_owner_user_id"), table_name="milestones")
    op.drop_index(op.f("ix_milestones_organization_id"), table_name="milestones")
    op.drop_index(op.f("ix_milestones_milestone_type"), table_name="milestones")
    op.drop_index(op.f("ix_milestones_is_key"), table_name="milestones")
    op.drop_index(op.f("ix_milestones_is_deleted"), table_name="milestones")
    op.drop_table("milestones")
    # ### end Alembic commands ###
