"""issue management schema

Revision ID: 68c52df15bb0
Revises: b5fa950fec91
Create Date: 2026-07-29 07:38:07.473806
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '68c52df15bb0'
down_revision: str | None = 'b5fa950fec91'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('issues',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=True),
    sa.Column('assignee_user_id', sa.Uuid(), nullable=True),
    sa.Column('reporter_user_id', sa.Uuid(), nullable=True),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.String(length=4000), nullable=False),
    sa.Column('issue_type', sa.Enum('bug', 'incident', 'improvement', 'question', 'other', name='issuetype', native_enum=False, length=20), nullable=False),
    sa.Column('severity', sa.Enum('low', 'medium', 'high', 'critical', name='issueseverity', native_enum=False, length=20), nullable=False),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', 'critical', name='issuepriority', native_enum=False, length=20), nullable=False),
    sa.Column('status', sa.Enum('open', 'in_progress', 'resolved', 'closed', name='issuestatus', native_enum=False, length=20), nullable=False),
    sa.Column('resolution', sa.String(length=4000), nullable=False),
    sa.Column('resolved_date', sa.Date(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('modified_by', sa.Uuid(), nullable=True),
    sa.Column('modified_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['assignee_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reporter_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'number', name='uq_issue_number')
    )
    op.create_index(op.f('ix_issues_assignee_user_id'), 'issues', ['assignee_user_id'], unique=False)
    op.create_index(op.f('ix_issues_is_deleted'), 'issues', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_issues_issue_type'), 'issues', ['issue_type'], unique=False)
    op.create_index(op.f('ix_issues_organization_id'), 'issues', ['organization_id'], unique=False)
    op.create_index(op.f('ix_issues_priority'), 'issues', ['priority'], unique=False)
    op.create_index(op.f('ix_issues_project_id'), 'issues', ['project_id'], unique=False)
    op.create_index(op.f('ix_issues_severity'), 'issues', ['severity'], unique=False)
    op.create_index(op.f('ix_issues_status'), 'issues', ['status'], unique=False)
    op.create_index(op.f('ix_issues_task_id'), 'issues', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_issues_task_id'), table_name='issues')
    op.drop_index(op.f('ix_issues_status'), table_name='issues')
    op.drop_index(op.f('ix_issues_severity'), table_name='issues')
    op.drop_index(op.f('ix_issues_project_id'), table_name='issues')
    op.drop_index(op.f('ix_issues_priority'), table_name='issues')
    op.drop_index(op.f('ix_issues_organization_id'), table_name='issues')
    op.drop_index(op.f('ix_issues_issue_type'), table_name='issues')
    op.drop_index(op.f('ix_issues_is_deleted'), table_name='issues')
    op.drop_index(op.f('ix_issues_assignee_user_id'), table_name='issues')
    op.drop_table('issues')
    # ### end Alembic commands ###
