"""add tech_stack to build_requests

Revision ID: 6b1f73d88ea6
Revises: 462677b59290
Create Date: 2026-09-21 06:09:01.665121
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

revision: str = "6b1f73d88ea6"
down_revision: str | None = "462677b59290"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "build_requests",
        sa.Column("tech_stack", sa.String(length=50), nullable=False, server_default=""),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("build_requests", "tech_stack")
    # ### end Alembic commands ###
