"""financial management schema

Revision ID: 732ba99ed24b
Revises: df79a114fb92
Create Date: 2026-07-29 06:17:33.526387
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

revision: str = "732ba99ed24b"
down_revision: str | None = "df79a114fb92"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "financial_entries",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column(
            "entry_type",
            sa.Enum(
                "budget",
                "forecast",
                "actual",
                name="financialentrytype",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column(
            "category",
            sa.Enum(
                "labor",
                "materials",
                "travel",
                "software",
                "hardware",
                "services",
                "overhead",
                "other",
                name="costcategory",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("entry_date", sa.Date(), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column("vendor", sa.String(length=200), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column(
            "created_date",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("modified_by", sa.Uuid(), nullable=True),
        sa.Column("modified_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_financial_entries_category"),
        "financial_entries",
        ["category"],
        unique=False,
    )
    op.create_index(
        op.f("ix_financial_entries_entry_type"),
        "financial_entries",
        ["entry_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_financial_entries_is_deleted"),
        "financial_entries",
        ["is_deleted"],
        unique=False,
    )
    op.create_index(
        op.f("ix_financial_entries_organization_id"),
        "financial_entries",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_financial_entries_project_id"),
        "financial_entries",
        ["project_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_financial_entries_project_id"), table_name="financial_entries")
    op.drop_index(op.f("ix_financial_entries_organization_id"), table_name="financial_entries")
    op.drop_index(op.f("ix_financial_entries_is_deleted"), table_name="financial_entries")
    op.drop_index(op.f("ix_financial_entries_entry_type"), table_name="financial_entries")
    op.drop_index(op.f("ix_financial_entries_category"), table_name="financial_entries")
    op.drop_table("financial_entries")
    # ### end Alembic commands ###
