"""add deployments table and run metrics

Revision ID: 7eb23ea33168
Revises: c8d830b56c03
Create Date: 2026-09-16 10:27:19.282249
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

revision: str = "7eb23ea33168"
down_revision: str | None = "c8d830b56c03"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "deployments",
        sa.Column("build_request_id", sa.Uuid(), nullable=False),
        sa.Column(
            "environment",
            sa.Enum(
                "dev",
                "staging",
                "production",
                name="environment",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "deployed",
                "failed",
                "rolled_back",
                name="deploymentstatus",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("release_version", sa.String(length=100), nullable=False),
        sa.Column("url", sa.String(length=1000), nullable=False),
        sa.Column("provider", sa.String(length=100), nullable=False),
        sa.Column("deployed_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column(
            "created_date",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("modified_by", sa.Uuid(), nullable=True),
        sa.Column("modified_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["build_request_id"], ["build_requests.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_deployments_build_request_id"),
        "deployments",
        ["build_request_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_deployments_environment"), "deployments", ["environment"], unique=False
    )
    op.create_index(op.f("ix_deployments_is_deleted"), "deployments", ["is_deleted"], unique=False)
    op.create_index(
        op.f("ix_deployments_organization_id"),
        "deployments",
        ["organization_id"],
        unique=False,
    )
    op.create_index(op.f("ix_deployments_status"), "deployments", ["status"], unique=False)
    op.add_column("pipeline_runs", sa.Column("metrics", sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("pipeline_runs", "metrics")
    op.drop_index(op.f("ix_deployments_status"), table_name="deployments")
    op.drop_index(op.f("ix_deployments_organization_id"), table_name="deployments")
    op.drop_index(op.f("ix_deployments_is_deleted"), table_name="deployments")
    op.drop_index(op.f("ix_deployments_environment"), table_name="deployments")
    op.drop_index(op.f("ix_deployments_build_request_id"), table_name="deployments")
    op.drop_table("deployments")
    # ### end Alembic commands ###
