"""meeting schema

Revision ID: 955572a952c6
Revises: af79b6de02b0
Create Date: 2026-07-29 12:21:44.553207
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '955572a952c6'
down_revision: str | None = 'af79b6de02b0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meetings',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('organizer_user_id', sa.Uuid(), nullable=True),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('meeting_type', sa.Enum('standup', 'planning', 'review', 'retrospective', 'status', 'stakeholder', 'kickoff', 'other', name='meetingtype', native_enum=False, length=20), nullable=False),
    sa.Column('status', sa.Enum('scheduled', 'in_progress', 'completed', 'cancelled', name='meetingstatus', native_enum=False, length=20), nullable=False),
    sa.Column('location', sa.String(length=500), nullable=False),
    sa.Column('agenda', sa.String(length=8000), nullable=False),
    sa.Column('minutes', sa.String(length=16000), nullable=False),
    sa.Column('scheduled_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scheduled_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actual_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('modified_by', sa.Uuid(), nullable=True),
    sa.Column('modified_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organizer_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'number', name='uq_meeting_number')
    )
    op.create_index(op.f('ix_meetings_is_deleted'), 'meetings', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_meetings_meeting_type'), 'meetings', ['meeting_type'], unique=False)
    op.create_index(op.f('ix_meetings_organization_id'), 'meetings', ['organization_id'], unique=False)
    op.create_index(op.f('ix_meetings_organizer_user_id'), 'meetings', ['organizer_user_id'], unique=False)
    op.create_index(op.f('ix_meetings_project_id'), 'meetings', ['project_id'], unique=False)
    op.create_index(op.f('ix_meetings_scheduled_start'), 'meetings', ['scheduled_start'], unique=False)
    op.create_index(op.f('ix_meetings_status'), 'meetings', ['status'], unique=False)
    op.create_table('meeting_attendees',
    sa.Column('meeting_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('organizer', 'required', 'optional', 'presenter', name='attendeerole', native_enum=False, length=20), nullable=False),
    sa.Column('response', sa.Enum('no_response', 'accepted', 'declined', 'tentative', name='attendeeresponse', native_enum=False, length=20), nullable=False),
    sa.Column('attended', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('modified_by', sa.Uuid(), nullable=True),
    sa.Column('modified_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meeting_id', 'user_id', name='uq_meeting_attendee')
    )
    op.create_index(op.f('ix_meeting_attendees_is_deleted'), 'meeting_attendees', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_meeting_attendees_meeting_id'), 'meeting_attendees', ['meeting_id'], unique=False)
    op.create_index(op.f('ix_meeting_attendees_organization_id'), 'meeting_attendees', ['organization_id'], unique=False)
    op.create_index(op.f('ix_meeting_attendees_user_id'), 'meeting_attendees', ['user_id'], unique=False)
    op.add_column('raid_actions', sa.Column('source_meeting_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_raid_actions_source_meeting_id'), 'raid_actions', ['source_meeting_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_raid_actions_source_meeting_id'), table_name='raid_actions')
    op.drop_column('raid_actions', 'source_meeting_id')
    op.drop_index(op.f('ix_meeting_attendees_user_id'), table_name='meeting_attendees')
    op.drop_index(op.f('ix_meeting_attendees_organization_id'), table_name='meeting_attendees')
    op.drop_index(op.f('ix_meeting_attendees_meeting_id'), table_name='meeting_attendees')
    op.drop_index(op.f('ix_meeting_attendees_is_deleted'), table_name='meeting_attendees')
    op.drop_table('meeting_attendees')
    op.drop_index(op.f('ix_meetings_status'), table_name='meetings')
    op.drop_index(op.f('ix_meetings_scheduled_start'), table_name='meetings')
    op.drop_index(op.f('ix_meetings_project_id'), table_name='meetings')
    op.drop_index(op.f('ix_meetings_organizer_user_id'), table_name='meetings')
    op.drop_index(op.f('ix_meetings_organization_id'), table_name='meetings')
    op.drop_index(op.f('ix_meetings_meeting_type'), table_name='meetings')
    op.drop_index(op.f('ix_meetings_is_deleted'), table_name='meetings')
    op.drop_table('meetings')
    # ### end Alembic commands ###
