"""add strategic initiatives goals kpis

Revision ID: 9bb525b4f598
Revises: 189ee006bb0a
Create Date: 2026-08-01 08:04:03.902191
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '9bb525b4f598'
down_revision: str | None = '189ee006bb0a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strategic_initiatives',
    sa.Column('portfolio_id', sa.Uuid(), nullable=True),
    sa.Column('sponsor_user_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('description', sa.String(length=4000), nullable=False),
    sa.Column('status', sa.Enum('proposed', 'active', 'on_hold', 'completed', 'cancelled', name='initiativestatus', native_enum=False, length=20), nullable=False),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', 'critical', name='initiativepriority', native_enum=False, length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('modified_by', sa.Uuid(), nullable=True),
    sa.Column('modified_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sponsor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategic_initiatives_is_deleted'), 'strategic_initiatives', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_strategic_initiatives_organization_id'), 'strategic_initiatives', ['organization_id'], unique=False)
    op.create_index(op.f('ix_strategic_initiatives_portfolio_id'), 'strategic_initiatives', ['portfolio_id'], unique=False)
    op.create_index(op.f('ix_strategic_initiatives_priority'), 'strategic_initiatives', ['priority'], unique=False)
    op.create_index(op.f('ix_strategic_initiatives_sponsor_user_id'), 'strategic_initiatives', ['sponsor_user_id'], unique=False)
    op.create_index(op.f('ix_strategic_initiatives_status'), 'strategic_initiatives', ['status'], unique=False)
    op.create_table('business_goals',
    sa.Column('initiative_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.String(length=4000), nullable=False),
    sa.Column('category', sa.Enum('growth', 'efficiency', 'customer', 'quality', 'financial', 'sustainability', 'other', name='goalcategory', native_enum=False, length=20), nullable=False),
    sa.Column('status', sa.Enum('not_started', 'in_progress', 'at_risk', 'achieved', 'missed', name='goalstatus', native_enum=False, length=20), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('modified_by', sa.Uuid(), nullable=True),
    sa.Column('modified_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['initiative_id'], ['strategic_initiatives.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_goals_category'), 'business_goals', ['category'], unique=False)
    op.create_index(op.f('ix_business_goals_initiative_id'), 'business_goals', ['initiative_id'], unique=False)
    op.create_index(op.f('ix_business_goals_is_deleted'), 'business_goals', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_business_goals_organization_id'), 'business_goals', ['organization_id'], unique=False)
    op.create_index(op.f('ix_business_goals_status'), 'business_goals', ['status'], unique=False)
    op.create_table('goal_kpis',
    sa.Column('goal_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('direction', sa.Enum('increase', 'decrease', name='kpidirection', native_enum=False, length=20), nullable=False),
    sa.Column('baseline_value', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('current_value', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('target_value', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('modified_by', sa.Uuid(), nullable=True),
    sa.Column('modified_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['business_goals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goal_kpis_goal_id'), 'goal_kpis', ['goal_id'], unique=False)
    op.create_index(op.f('ix_goal_kpis_is_deleted'), 'goal_kpis', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_goal_kpis_organization_id'), 'goal_kpis', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_goal_kpis_organization_id'), table_name='goal_kpis')
    op.drop_index(op.f('ix_goal_kpis_is_deleted'), table_name='goal_kpis')
    op.drop_index(op.f('ix_goal_kpis_goal_id'), table_name='goal_kpis')
    op.drop_table('goal_kpis')
    op.drop_index(op.f('ix_business_goals_status'), table_name='business_goals')
    op.drop_index(op.f('ix_business_goals_organization_id'), table_name='business_goals')
    op.drop_index(op.f('ix_business_goals_is_deleted'), table_name='business_goals')
    op.drop_index(op.f('ix_business_goals_initiative_id'), table_name='business_goals')
    op.drop_index(op.f('ix_business_goals_category'), table_name='business_goals')
    op.drop_table('business_goals')
    op.drop_index(op.f('ix_strategic_initiatives_status'), table_name='strategic_initiatives')
    op.drop_index(op.f('ix_strategic_initiatives_sponsor_user_id'), table_name='strategic_initiatives')
    op.drop_index(op.f('ix_strategic_initiatives_priority'), table_name='strategic_initiatives')
    op.drop_index(op.f('ix_strategic_initiatives_portfolio_id'), table_name='strategic_initiatives')
    op.drop_index(op.f('ix_strategic_initiatives_organization_id'), table_name='strategic_initiatives')
    op.drop_index(op.f('ix_strategic_initiatives_is_deleted'), table_name='strategic_initiatives')
    op.drop_table('strategic_initiatives')
    # ### end Alembic commands ###
