"""raid log schema

Revision ID: a3cc745f73da
Revises: 68c52df15bb0
Create Date: 2026-07-29 08:00:36.130094
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

revision: str = "a3cc745f73da"
down_revision: str | None = "68c52df15bb0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "raid_actions",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("owner_user_id", sa.Uuid(), nullable=True),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("description", sa.String(length=4000), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "open",
                "in_progress",
                "done",
                "cancelled",
                name="actionstatus",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column(
            "priority",
            sa.Enum(
                "low",
                "medium",
                "high",
                "critical",
                name="actionpriority",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column("completed_date", sa.Date(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column(
            "created_date",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("modified_by", sa.Uuid(), nullable=True),
        sa.Column("modified_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["owner_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "number", name="uq_action_number"),
    )
    op.create_index(
        op.f("ix_raid_actions_is_deleted"), "raid_actions", ["is_deleted"], unique=False
    )
    op.create_index(
        op.f("ix_raid_actions_organization_id"),
        "raid_actions",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_raid_actions_owner_user_id"),
        "raid_actions",
        ["owner_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_raid_actions_project_id"), "raid_actions", ["project_id"], unique=False
    )
    op.create_index(op.f("ix_raid_actions_status"), "raid_actions", ["status"], unique=False)
    op.create_table(
        "raid_decisions",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("decided_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("description", sa.String(length=4000), nullable=False),
        sa.Column("rationale", sa.String(length=4000), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "proposed",
                "decided",
                "superseded",
                "rejected",
                name="decisionstatus",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("decision_date", sa.Date(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column(
            "created_date",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("modified_by", sa.Uuid(), nullable=True),
        sa.Column("modified_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["decided_by_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "number", name="uq_decision_number"),
    )
    op.create_index(
        op.f("ix_raid_decisions_is_deleted"),
        "raid_decisions",
        ["is_deleted"],
        unique=False,
    )
    op.create_index(
        op.f("ix_raid_decisions_organization_id"),
        "raid_decisions",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_raid_decisions_project_id"),
        "raid_decisions",
        ["project_id"],
        unique=False,
    )
    op.create_index(op.f("ix_raid_decisions_status"), "raid_decisions", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_raid_decisions_status"), table_name="raid_decisions")
    op.drop_index(op.f("ix_raid_decisions_project_id"), table_name="raid_decisions")
    op.drop_index(op.f("ix_raid_decisions_organization_id"), table_name="raid_decisions")
    op.drop_index(op.f("ix_raid_decisions_is_deleted"), table_name="raid_decisions")
    op.drop_table("raid_decisions")
    op.drop_index(op.f("ix_raid_actions_status"), table_name="raid_actions")
    op.drop_index(op.f("ix_raid_actions_project_id"), table_name="raid_actions")
    op.drop_index(op.f("ix_raid_actions_owner_user_id"), table_name="raid_actions")
    op.drop_index(op.f("ix_raid_actions_organization_id"), table_name="raid_actions")
    op.drop_index(op.f("ix_raid_actions_is_deleted"), table_name="raid_actions")
    op.drop_table("raid_actions")
    # ### end Alembic commands ###
