"""program management schema

Revision ID: a766a2059a22
Revises: d14a2ba80829
Create Date: 2026-07-28 13:29:11.981586
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

revision: str = "a766a2059a22"
down_revision: str | None = "d14a2ba80829"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "programs",
        sa.Column("portfolio_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("description", sa.String(length=1000), nullable=False),
        sa.Column("manager_user_id", sa.Uuid(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "proposed",
                "active",
                "on_hold",
                "closed",
                "cancelled",
                name="programstatus",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column(
            "priority",
            sa.Enum(
                "low",
                "medium",
                "high",
                "critical",
                name="programpriority",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column(
            "health",
            sa.Enum(
                "on_track",
                "at_risk",
                "off_track",
                name="programhealth",
                native_enum=False,
                length=20,
            ),
            nullable=True,
        ),
        sa.Column("planned_budget", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column(
            "created_date",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("modified_by", sa.Uuid(), nullable=True),
        sa.Column("modified_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["manager_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["portfolio_id"], ["portfolios.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "code", name="uq_program_code"),
    )
    op.create_index(op.f("ix_programs_is_deleted"), "programs", ["is_deleted"], unique=False)
    op.create_index(
        op.f("ix_programs_organization_id"),
        "programs",
        ["organization_id"],
        unique=False,
    )
    op.create_index(op.f("ix_programs_portfolio_id"), "programs", ["portfolio_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_programs_portfolio_id"), table_name="programs")
    op.drop_index(op.f("ix_programs_organization_id"), table_name="programs")
    op.drop_index(op.f("ix_programs_is_deleted"), table_name="programs")
    op.drop_table("programs")
    # ### end Alembic commands ###
