"""copilot schema

Revision ID: a97574a5d8ea
Revises: 15addb18d376
Create Date: 2026-07-30 04:37:53.983396
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'a97574a5d8ea'
down_revision: str | None = '15addb18d376'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('copilot_conversations',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('modified_by', sa.Uuid(), nullable=True),
    sa.Column('modified_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_copilot_conversations_is_deleted'), 'copilot_conversations', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_copilot_conversations_organization_id'), 'copilot_conversations', ['organization_id'], unique=False)
    op.create_index(op.f('ix_copilot_conversations_user_id'), 'copilot_conversations', ['user_id'], unique=False)
    op.create_table('copilot_messages',
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('user', 'assistant', name='messagerole', native_enum=False, length=20), nullable=False),
    sa.Column('content', sa.String(length=8000), nullable=False),
    sa.Column('intent', sa.Enum('project_status', 'raid_summary', 'milestone_status', 'timesheet_hours', 'financial_summary', 'portfolio_overview', 'help', 'needs_project', 'needs_portfolio', 'unknown', name='copilotintent', native_enum=False, length=20), nullable=True),
    sa.Column('grounding', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('modified_by', sa.Uuid(), nullable=True),
    sa.Column('modified_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['copilot_conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_copilot_messages_conversation_id'), 'copilot_messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_copilot_messages_is_deleted'), 'copilot_messages', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_copilot_messages_organization_id'), 'copilot_messages', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_copilot_messages_organization_id'), table_name='copilot_messages')
    op.drop_index(op.f('ix_copilot_messages_is_deleted'), table_name='copilot_messages')
    op.drop_index(op.f('ix_copilot_messages_conversation_id'), table_name='copilot_messages')
    op.drop_table('copilot_messages')
    op.drop_index(op.f('ix_copilot_conversations_user_id'), table_name='copilot_conversations')
    op.drop_index(op.f('ix_copilot_conversations_organization_id'), table_name='copilot_conversations')
    op.drop_index(op.f('ix_copilot_conversations_is_deleted'), table_name='copilot_conversations')
    op.drop_table('copilot_conversations')
    # ### end Alembic commands ###
