"""add project_kpis table

Revision ID: aa1bd523f704
Revises: 78bba1894c0f
Create Date: 2026-09-26 13:52:54.484649
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'aa1bd523f704'
down_revision: str | None = '78bba1894c0f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_kpis',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('direction', sa.Enum('increase', 'decrease', name='kpidirection', native_enum=False, length=20), nullable=False),
    sa.Column('baseline_value', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('current_value', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('target_value', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('modified_by', sa.Uuid(), nullable=True),
    sa.Column('modified_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_kpis_is_deleted'), 'project_kpis', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_project_kpis_organization_id'), 'project_kpis', ['organization_id'], unique=False)
    op.create_index(op.f('ix_project_kpis_project_id'), 'project_kpis', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_kpis_project_id'), table_name='project_kpis')
    op.drop_index(op.f('ix_project_kpis_organization_id'), table_name='project_kpis')
    op.drop_index(op.f('ix_project_kpis_is_deleted'), table_name='project_kpis')
    op.drop_table('project_kpis')
    # ### end Alembic commands ###
