"""risk management schema

Revision ID: b5fa950fec91
Revises: 732ba99ed24b
Create Date: 2026-07-29 06:32:02.556265
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

revision: str = "b5fa950fec91"
down_revision: str | None = "732ba99ed24b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "risks",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("owner_user_id", sa.Uuid(), nullable=True),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("description", sa.String(length=4000), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "technical",
                "schedule",
                "cost",
                "resource",
                "scope",
                "external",
                "organizational",
                "other",
                name="riskcategory",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "identified",
                "analyzing",
                "mitigating",
                "monitoring",
                "closed",
                name="riskstatus",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column(
            "response_strategy",
            sa.Enum(
                "avoid",
                "mitigate",
                "transfer",
                "accept",
                "escalate",
                name="riskresponse",
                native_enum=False,
                length=20,
            ),
            nullable=True,
        ),
        sa.Column("probability", sa.Integer(), nullable=False),
        sa.Column("impact", sa.Integer(), nullable=False),
        sa.Column("risk_score", sa.Integer(), nullable=False),
        sa.Column(
            "severity",
            sa.Enum(
                "low",
                "medium",
                "high",
                "critical",
                name="riskseverity",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("mitigation_plan", sa.String(length=4000), nullable=False),
        sa.Column("target_date", sa.Date(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column(
            "created_date",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("modified_by", sa.Uuid(), nullable=True),
        sa.Column("modified_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["owner_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "number", name="uq_risk_number"),
    )
    op.create_index(op.f("ix_risks_category"), "risks", ["category"], unique=False)
    op.create_index(op.f("ix_risks_is_deleted"), "risks", ["is_deleted"], unique=False)
    op.create_index(op.f("ix_risks_organization_id"), "risks", ["organization_id"], unique=False)
    op.create_index(op.f("ix_risks_owner_user_id"), "risks", ["owner_user_id"], unique=False)
    op.create_index(op.f("ix_risks_project_id"), "risks", ["project_id"], unique=False)
    op.create_index(op.f("ix_risks_risk_score"), "risks", ["risk_score"], unique=False)
    op.create_index(op.f("ix_risks_severity"), "risks", ["severity"], unique=False)
    op.create_index(op.f("ix_risks_status"), "risks", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_risks_status"), table_name="risks")
    op.drop_index(op.f("ix_risks_severity"), table_name="risks")
    op.drop_index(op.f("ix_risks_risk_score"), table_name="risks")
    op.drop_index(op.f("ix_risks_project_id"), table_name="risks")
    op.drop_index(op.f("ix_risks_owner_user_id"), table_name="risks")
    op.drop_index(op.f("ix_risks_organization_id"), table_name="risks")
    op.drop_index(op.f("ix_risks_is_deleted"), table_name="risks")
    op.drop_index(op.f("ix_risks_category"), table_name="risks")
    op.drop_table("risks")
    # ### end Alembic commands ###
