"""add workflow tables

Revision ID: b9d06ab258c5
Revises: 9bb525b4f598
Create Date: 2026-08-02 03:40:26.051671
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'b9d06ab258c5'
down_revision: str | None = '9bb525b4f598'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow_definitions',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('modified_by', sa.Uuid(), nullable=True),
    sa.Column('modified_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_definitions_entity_type'), 'workflow_definitions', ['entity_type'], unique=False)
    op.create_index(op.f('ix_workflow_definitions_is_deleted'), 'workflow_definitions', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_workflow_definitions_name'), 'workflow_definitions', ['name'], unique=False)
    op.create_index(op.f('ix_workflow_definitions_organization_id'), 'workflow_definitions', ['organization_id'], unique=False)
    op.create_table('workflow_stages',
    sa.Column('definition_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('requires_approval', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('modified_by', sa.Uuid(), nullable=True),
    sa.Column('modified_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['definition_id'], ['workflow_definitions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_stages_definition_id'), 'workflow_stages', ['definition_id'], unique=False)
    op.create_index(op.f('ix_workflow_stages_is_deleted'), 'workflow_stages', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_workflow_stages_organization_id'), 'workflow_stages', ['organization_id'], unique=False)
    op.create_table('workflow_instances',
    sa.Column('definition_id', sa.Uuid(), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('current_stage_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('in_progress', 'completed', 'rejected', 'cancelled', name='workflowstatus', native_enum=False, length=20), nullable=False),
    sa.Column('started_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('modified_by', sa.Uuid(), nullable=True),
    sa.Column('modified_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['current_stage_id'], ['workflow_stages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['definition_id'], ['workflow_definitions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_instances_definition_id'), 'workflow_instances', ['definition_id'], unique=False)
    op.create_index(op.f('ix_workflow_instances_entity_id'), 'workflow_instances', ['entity_id'], unique=False)
    op.create_index(op.f('ix_workflow_instances_entity_type'), 'workflow_instances', ['entity_type'], unique=False)
    op.create_index(op.f('ix_workflow_instances_is_deleted'), 'workflow_instances', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_workflow_instances_organization_id'), 'workflow_instances', ['organization_id'], unique=False)
    op.create_index(op.f('ix_workflow_instances_status'), 'workflow_instances', ['status'], unique=False)
    op.create_table('gate_approvals',
    sa.Column('instance_id', sa.Uuid(), nullable=False),
    sa.Column('stage_id', sa.Uuid(), nullable=True),
    sa.Column('decision', sa.Enum('approved', 'rejected', name='approvaldecision', native_enum=False, length=20), nullable=False),
    sa.Column('approver_user_id', sa.Uuid(), nullable=True),
    sa.Column('comment', sa.String(length=2000), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('modified_by', sa.Uuid(), nullable=True),
    sa.Column('modified_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['instance_id'], ['workflow_instances.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stage_id'], ['workflow_stages.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gate_approvals_instance_id'), 'gate_approvals', ['instance_id'], unique=False)
    op.create_index(op.f('ix_gate_approvals_is_deleted'), 'gate_approvals', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_gate_approvals_organization_id'), 'gate_approvals', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gate_approvals_organization_id'), table_name='gate_approvals')
    op.drop_index(op.f('ix_gate_approvals_is_deleted'), table_name='gate_approvals')
    op.drop_index(op.f('ix_gate_approvals_instance_id'), table_name='gate_approvals')
    op.drop_table('gate_approvals')
    op.drop_index(op.f('ix_workflow_instances_status'), table_name='workflow_instances')
    op.drop_index(op.f('ix_workflow_instances_organization_id'), table_name='workflow_instances')
    op.drop_index(op.f('ix_workflow_instances_is_deleted'), table_name='workflow_instances')
    op.drop_index(op.f('ix_workflow_instances_entity_type'), table_name='workflow_instances')
    op.drop_index(op.f('ix_workflow_instances_entity_id'), table_name='workflow_instances')
    op.drop_index(op.f('ix_workflow_instances_definition_id'), table_name='workflow_instances')
    op.drop_table('workflow_instances')
    op.drop_index(op.f('ix_workflow_stages_organization_id'), table_name='workflow_stages')
    op.drop_index(op.f('ix_workflow_stages_is_deleted'), table_name='workflow_stages')
    op.drop_index(op.f('ix_workflow_stages_definition_id'), table_name='workflow_stages')
    op.drop_table('workflow_stages')
    op.drop_index(op.f('ix_workflow_definitions_organization_id'), table_name='workflow_definitions')
    op.drop_index(op.f('ix_workflow_definitions_name'), table_name='workflow_definitions')
    op.drop_index(op.f('ix_workflow_definitions_is_deleted'), table_name='workflow_definitions')
    op.drop_index(op.f('ix_workflow_definitions_entity_type'), table_name='workflow_definitions')
    op.drop_table('workflow_definitions')
    # ### end Alembic commands ###
