"""dependency schema

Revision ID: c20536e0a75b
Revises: 533548b7b94a
Create Date: 2026-07-29 10:13:36.962675
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'c20536e0a75b'
down_revision: str | None = '533548b7b94a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dependencies',
    sa.Column('entity_type', sa.Enum('task', 'project', name='dependencyentitytype', native_enum=False, length=20), nullable=False),
    sa.Column('predecessor_id', sa.Uuid(), nullable=False),
    sa.Column('successor_id', sa.Uuid(), nullable=False),
    sa.Column('dependency_type', sa.Enum('finish_to_start', 'start_to_start', 'finish_to_finish', 'start_to_finish', name='dependencytype', native_enum=False, length=20), nullable=False),
    sa.Column('lag_days', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('modified_by', sa.Uuid(), nullable=True),
    sa.Column('modified_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'entity_type', 'predecessor_id', 'successor_id', name='uq_dependency_edge')
    )
    op.create_index(op.f('ix_dependencies_entity_type'), 'dependencies', ['entity_type'], unique=False)
    op.create_index(op.f('ix_dependencies_is_deleted'), 'dependencies', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_dependencies_organization_id'), 'dependencies', ['organization_id'], unique=False)
    op.create_index(op.f('ix_dependencies_predecessor_id'), 'dependencies', ['predecessor_id'], unique=False)
    op.create_index(op.f('ix_dependencies_successor_id'), 'dependencies', ['successor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dependencies_successor_id'), table_name='dependencies')
    op.drop_index(op.f('ix_dependencies_predecessor_id'), table_name='dependencies')
    op.drop_index(op.f('ix_dependencies_organization_id'), table_name='dependencies')
    op.drop_index(op.f('ix_dependencies_is_deleted'), table_name='dependencies')
    op.drop_index(op.f('ix_dependencies_entity_type'), table_name='dependencies')
    op.drop_table('dependencies')
    # ### end Alembic commands ###
