"""add sso role_mappings

Revision ID: c483e8e45ece
Revises: fd646c7883cc
Create Date: 2026-09-27 04:02:56.429670
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

revision: str = "c483e8e45ece"
down_revision: str | None = "fd646c7883cc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("sso_configurations", sa.Column("role_mappings", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sso_configurations", "role_mappings")
    # ### end Alembic commands ###
