"""add generated_output to build_requests

Revision ID: c8d830b56c03
Revises: 2406e9f2061c
Create Date: 2026-09-15 09:13:00.840376
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

revision: str = "c8d830b56c03"
down_revision: str | None = "2406e9f2061c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("build_requests", sa.Column("generated_output", sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("build_requests", "generated_output")
    # ### end Alembic commands ###
