"""portfolio management schema

Revision ID: d14a2ba80829
Revises: 466e8c2bd60d
Create Date: 2026-07-28 12:05:45.084534
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'd14a2ba80829'
down_revision: str | None = '466e8c2bd60d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolios',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('owner_user_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('proposed', 'active', 'on_hold', 'closed', 'cancelled', name='portfoliostatus', native_enum=False, length=20), nullable=False),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', 'critical', name='portfoliopriority', native_enum=False, length=20), nullable=False),
    sa.Column('health', sa.Enum('on_track', 'at_risk', 'off_track', name='portfoliohealth', native_enum=False, length=20), nullable=True),
    sa.Column('planned_budget', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('modified_by', sa.Uuid(), nullable=True),
    sa.Column('modified_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'code', name='uq_portfolio_code')
    )
    op.create_index(op.f('ix_portfolios_is_deleted'), 'portfolios', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_portfolios_organization_id'), 'portfolios', ['organization_id'], unique=False)
    op.create_table('portfolio_objectives',
    sa.Column('portfolio_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('modified_by', sa.Uuid(), nullable=True),
    sa.Column('modified_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolio_objectives_is_deleted'), 'portfolio_objectives', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_portfolio_objectives_organization_id'), 'portfolio_objectives', ['organization_id'], unique=False)
    op.create_index(op.f('ix_portfolio_objectives_portfolio_id'), 'portfolio_objectives', ['portfolio_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_portfolio_objectives_portfolio_id'), table_name='portfolio_objectives')
    op.drop_index(op.f('ix_portfolio_objectives_organization_id'), table_name='portfolio_objectives')
    op.drop_index(op.f('ix_portfolio_objectives_is_deleted'), table_name='portfolio_objectives')
    op.drop_table('portfolio_objectives')
    op.drop_index(op.f('ix_portfolios_organization_id'), table_name='portfolios')
    op.drop_index(op.f('ix_portfolios_is_deleted'), table_name='portfolios')
    op.drop_table('portfolios')
    # ### end Alembic commands ###
