"""timesheet schema

Revision ID: dd493f1a0f53
Revises: 5b9b89fa940d
Create Date: 2026-07-29 11:03:27.434553
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

revision: str = "dd493f1a0f53"
down_revision: str | None = "5b9b89fa940d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "time_entries",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("task_id", sa.Uuid(), nullable=True),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("approver_user_id", sa.Uuid(), nullable=True),
        sa.Column("work_date", sa.Date(), nullable=False),
        sa.Column("hours", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column("billable", sa.Boolean(), nullable=False),
        sa.Column(
            "activity_type",
            sa.Enum(
                "development",
                "design",
                "testing",
                "meeting",
                "management",
                "support",
                "other",
                name="activitytype",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("description", sa.String(length=2000), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "submitted",
                "approved",
                "rejected",
                name="timeentrystatus",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("decision_notes", sa.String(length=2000), nullable=False),
        sa.Column("decided_date", sa.Date(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column(
            "created_date",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("modified_by", sa.Uuid(), nullable=True),
        sa.Column("modified_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["approver_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_time_entries_activity_type"),
        "time_entries",
        ["activity_type"],
        unique=False,
    )
    op.create_index(op.f("ix_time_entries_billable"), "time_entries", ["billable"], unique=False)
    op.create_index(
        op.f("ix_time_entries_is_deleted"), "time_entries", ["is_deleted"], unique=False
    )
    op.create_index(
        op.f("ix_time_entries_organization_id"),
        "time_entries",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_time_entries_project_id"), "time_entries", ["project_id"], unique=False
    )
    op.create_index(op.f("ix_time_entries_status"), "time_entries", ["status"], unique=False)
    op.create_index(op.f("ix_time_entries_task_id"), "time_entries", ["task_id"], unique=False)
    op.create_index(op.f("ix_time_entries_user_id"), "time_entries", ["user_id"], unique=False)
    op.create_index(op.f("ix_time_entries_work_date"), "time_entries", ["work_date"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_time_entries_work_date"), table_name="time_entries")
    op.drop_index(op.f("ix_time_entries_user_id"), table_name="time_entries")
    op.drop_index(op.f("ix_time_entries_task_id"), table_name="time_entries")
    op.drop_index(op.f("ix_time_entries_status"), table_name="time_entries")
    op.drop_index(op.f("ix_time_entries_project_id"), table_name="time_entries")
    op.drop_index(op.f("ix_time_entries_organization_id"), table_name="time_entries")
    op.drop_index(op.f("ix_time_entries_is_deleted"), table_name="time_entries")
    op.drop_index(op.f("ix_time_entries_billable"), table_name="time_entries")
    op.drop_index(op.f("ix_time_entries_activity_type"), table_name="time_entries")
    op.drop_table("time_entries")
    # ### end Alembic commands ###
