"""resource management schema

Revision ID: df79a114fb92
Revises: 0f69215c4b24
Create Date: 2026-07-29 03:43:39.759952
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

revision: str = "df79a114fb92"
down_revision: str | None = "0f69215c4b24"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "resources",
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("department_id", sa.Uuid(), nullable=True),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column(
            "resource_type",
            sa.Enum(
                "employee",
                "contractor",
                "vendor",
                "equipment",
                name="resourcetype",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("capacity_hours_per_week", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column("cost_rate", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("skills", sa.JSON(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column(
            "created_date",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("modified_by", sa.Uuid(), nullable=True),
        sa.Column("modified_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["department_id"], ["departments.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_resources_is_deleted"), "resources", ["is_deleted"], unique=False)
    op.create_index(
        op.f("ix_resources_organization_id"),
        "resources",
        ["organization_id"],
        unique=False,
    )
    op.create_index(op.f("ix_resources_user_id"), "resources", ["user_id"], unique=False)
    op.create_table(
        "resource_allocations",
        sa.Column("resource_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("allocation_percent", sa.Integer(), nullable=False),
        sa.Column("role_label", sa.String(length=100), nullable=False),
        sa.Column("notes", sa.String(length=500), nullable=False),
        sa.Column("custom_fields", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column(
            "created_date",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("modified_by", sa.Uuid(), nullable=True),
        sa.Column("modified_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["resource_id"], ["resources.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_resource_allocations_is_deleted"),
        "resource_allocations",
        ["is_deleted"],
        unique=False,
    )
    op.create_index(
        op.f("ix_resource_allocations_organization_id"),
        "resource_allocations",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_resource_allocations_project_id"),
        "resource_allocations",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_resource_allocations_resource_id"),
        "resource_allocations",
        ["resource_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_resource_allocations_resource_id"), table_name="resource_allocations")
    op.drop_index(op.f("ix_resource_allocations_project_id"), table_name="resource_allocations")
    op.drop_index(
        op.f("ix_resource_allocations_organization_id"),
        table_name="resource_allocations",
    )
    op.drop_index(op.f("ix_resource_allocations_is_deleted"), table_name="resource_allocations")
    op.drop_table("resource_allocations")
    op.drop_index(op.f("ix_resources_user_id"), table_name="resources")
    op.drop_index(op.f("ix_resources_organization_id"), table_name="resources")
    op.drop_index(op.f("ix_resources_is_deleted"), table_name="resources")
    op.drop_table("resources")
    # ### end Alembic commands ###
