"""add gate_require_tests to build_requests

Revision ID: e369f1f121e9
Revises: 6b1f73d88ea6
Create Date: 2026-09-21 08:23:14.579926
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'e369f1f121e9'
down_revision: str | None = '6b1f73d88ea6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('build_requests', sa.Column('gate_require_tests', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('build_requests', 'gate_require_tests')
    # ### end Alembic commands ###
