"""add benefits table

Revision ID: e80fb33685b1
Revises: a97574a5d8ea
Create Date: 2026-07-31 18:06:49.092276
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'e80fb33685b1'
down_revision: str | None = 'a97574a5d8ea'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('benefits',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('owner_user_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.String(length=4000), nullable=False),
    sa.Column('category', sa.Enum('financial', 'operational', 'strategic', 'customer', 'compliance', 'risk_reduction', name='benefitcategory', native_enum=False, length=20), nullable=False),
    sa.Column('status', sa.Enum('planned', 'in_progress', 'partially_realized', 'realized', 'at_risk', 'missed', name='benefitstatus', native_enum=False, length=20), nullable=False),
    sa.Column('target_value', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('realized_value', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('investment_cost', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('realized_date', sa.Date(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('modified_by', sa.Uuid(), nullable=True),
    sa.Column('modified_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_benefits_category'), 'benefits', ['category'], unique=False)
    op.create_index(op.f('ix_benefits_is_deleted'), 'benefits', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_benefits_organization_id'), 'benefits', ['organization_id'], unique=False)
    op.create_index(op.f('ix_benefits_owner_user_id'), 'benefits', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_benefits_project_id'), 'benefits', ['project_id'], unique=False)
    op.create_index(op.f('ix_benefits_status'), 'benefits', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_benefits_status'), table_name='benefits')
    op.drop_index(op.f('ix_benefits_project_id'), table_name='benefits')
    op.drop_index(op.f('ix_benefits_owner_user_id'), table_name='benefits')
    op.drop_index(op.f('ix_benefits_organization_id'), table_name='benefits')
    op.drop_index(op.f('ix_benefits_is_deleted'), table_name='benefits')
    op.drop_index(op.f('ix_benefits_category'), table_name='benefits')
    op.drop_table('benefits')
    # ### end Alembic commands ###
