"""project management schema

Revision ID: f4d3fc7b7941
Revises: a766a2059a22
Create Date: 2026-07-28 14:17:13.995542
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

revision: str = "f4d3fc7b7941"
down_revision: str | None = "a766a2059a22"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "projects",
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.String(length=2000), nullable=False),
        sa.Column("portfolio_id", sa.Uuid(), nullable=True),
        sa.Column("program_id", sa.Uuid(), nullable=True),
        sa.Column("department_id", sa.Uuid(), nullable=True),
        sa.Column("sponsor_user_id", sa.Uuid(), nullable=True),
        sa.Column("manager_user_id", sa.Uuid(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "proposed",
                "active",
                "on_hold",
                "closed",
                "cancelled",
                name="projectstatus",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column(
            "stage",
            sa.Enum(
                "initiation",
                "planning",
                "execution",
                "monitoring",
                "closing",
                name="projectstage",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column(
            "priority",
            sa.Enum(
                "low",
                "medium",
                "high",
                "critical",
                name="projectpriority",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column(
            "health",
            sa.Enum(
                "on_track",
                "at_risk",
                "off_track",
                name="projecthealth",
                native_enum=False,
                length=20,
            ),
            nullable=True,
        ),
        sa.Column("budget", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("forecast", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("actual_cost", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("baseline_start_date", sa.Date(), nullable=True),
        sa.Column("baseline_end_date", sa.Date(), nullable=True),
        sa.Column("progress_percent", sa.Integer(), nullable=False),
        sa.Column("risk_score", sa.Integer(), nullable=False),
        sa.Column("issue_count", sa.Integer(), nullable=False),
        sa.Column("tags", sa.JSON(), nullable=False),
        sa.Column("custom_fields", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column(
            "created_date",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("modified_by", sa.Uuid(), nullable=True),
        sa.Column("modified_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["department_id"], ["departments.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["manager_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["portfolio_id"], ["portfolios.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["program_id"], ["programs.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["sponsor_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "code", name="uq_project_code"),
        sa.UniqueConstraint("organization_id", "number", name="uq_project_number"),
    )
    op.create_index(op.f("ix_projects_is_deleted"), "projects", ["is_deleted"], unique=False)
    op.create_index(
        op.f("ix_projects_organization_id"),
        "projects",
        ["organization_id"],
        unique=False,
    )
    op.create_index(op.f("ix_projects_portfolio_id"), "projects", ["portfolio_id"], unique=False)
    op.create_index(op.f("ix_projects_program_id"), "projects", ["program_id"], unique=False)
    op.create_table(
        "project_comments",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("author_user_id", sa.Uuid(), nullable=False),
        sa.Column("body", sa.String(length=4000), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column(
            "created_date",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("modified_by", sa.Uuid(), nullable=True),
        sa.Column("modified_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["author_user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_project_comments_is_deleted"),
        "project_comments",
        ["is_deleted"],
        unique=False,
    )
    op.create_index(
        op.f("ix_project_comments_organization_id"),
        "project_comments",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_project_comments_project_id"),
        "project_comments",
        ["project_id"],
        unique=False,
    )
    op.create_table(
        "project_team_members",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("role_label", sa.String(length=100), nullable=False),
        sa.Column("allocation_percent", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column(
            "created_date",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("modified_by", sa.Uuid(), nullable=True),
        sa.Column("modified_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "user_id", name="uq_project_member"),
    )
    op.create_index(
        op.f("ix_project_team_members_is_deleted"),
        "project_team_members",
        ["is_deleted"],
        unique=False,
    )
    op.create_index(
        op.f("ix_project_team_members_organization_id"),
        "project_team_members",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_project_team_members_project_id"),
        "project_team_members",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_project_team_members_user_id"),
        "project_team_members",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_project_team_members_user_id"), table_name="project_team_members")
    op.drop_index(op.f("ix_project_team_members_project_id"), table_name="project_team_members")
    op.drop_index(
        op.f("ix_project_team_members_organization_id"),
        table_name="project_team_members",
    )
    op.drop_index(op.f("ix_project_team_members_is_deleted"), table_name="project_team_members")
    op.drop_table("project_team_members")
    op.drop_index(op.f("ix_project_comments_project_id"), table_name="project_comments")
    op.drop_index(op.f("ix_project_comments_organization_id"), table_name="project_comments")
    op.drop_index(op.f("ix_project_comments_is_deleted"), table_name="project_comments")
    op.drop_table("project_comments")
    op.drop_index(op.f("ix_projects_program_id"), table_name="projects")
    op.drop_index(op.f("ix_projects_portfolio_id"), table_name="projects")
    op.drop_index(op.f("ix_projects_organization_id"), table_name="projects")
    op.drop_index(op.f("ix_projects_is_deleted"), table_name="projects")
    op.drop_table("projects")
    # ### end Alembic commands ###
