"""add jira_sync_logs table

Revision ID: fd646c7883cc
Revises: aa1bd523f704
Create Date: 2026-09-27 03:58:09.099461
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

revision: str = "fd646c7883cc"
down_revision: str | None = "aa1bd523f704"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "jira_sync_logs",
        sa.Column(
            "direction",
            sa.Enum(
                "inbound",
                "import",
                "outbound",
                "test",
                name="syncdirection",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("success", "error", name="syncstatus", native_enum=False, length=20),
            nullable=False,
        ),
        sa.Column("summary", sa.String(length=1000), nullable=False),
        sa.Column("created_count", sa.Integer(), nullable=False),
        sa.Column("updated_count", sa.Integer(), nullable=False),
        sa.Column("skipped_count", sa.Integer(), nullable=False),
        sa.Column("failed_count", sa.Integer(), nullable=False),
        sa.Column("external_ref", sa.String(length=200), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column(
            "created_date",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("modified_by", sa.Uuid(), nullable=True),
        sa.Column("modified_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_jira_sync_logs_direction"),
        "jira_sync_logs",
        ["direction"],
        unique=False,
    )
    op.create_index(
        op.f("ix_jira_sync_logs_is_deleted"),
        "jira_sync_logs",
        ["is_deleted"],
        unique=False,
    )
    op.create_index(
        op.f("ix_jira_sync_logs_organization_id"),
        "jira_sync_logs",
        ["organization_id"],
        unique=False,
    )
    op.create_index(op.f("ix_jira_sync_logs_status"), "jira_sync_logs", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_jira_sync_logs_status"), table_name="jira_sync_logs")
    op.drop_index(op.f("ix_jira_sync_logs_organization_id"), table_name="jira_sync_logs")
    op.drop_index(op.f("ix_jira_sync_logs_is_deleted"), table_name="jira_sync_logs")
    op.drop_index(op.f("ix_jira_sync_logs_direction"), table_name="jira_sync_logs")
    op.drop_table("jira_sync_logs")
    # ### end Alembic commands ###
