"""Seed definitions for the access-control model.

``PERMISSION_CATALOGUE`` is the canonical list of permissions recognised by the
platform. ``SYSTEM_ROLES`` maps each seeded role to the permission codes it
grants. These are applied per organization at registration time and reconciled
by the ``seed`` management command / Alembic data migration.
"""

from __future__ import annotations

# resource:action -> human description
PERMISSION_CATALOGUE: dict[str, str] = {
    "organization:read": "View organization settings",
    "organization:update": "Modify organization settings",
    "user:create": "Invite and create users",
    "user:read": "View users",
    "user:update": "Modify users",
    "user:delete": "Deactivate users",
    "role:create": "Create roles",
    "role:read": "View roles",
    "role:update": "Modify roles",
    "role:delete": "Delete roles",
    "project:create": "Create projects",
    "project:read": "View projects",
    "project:update": "Modify projects",
    "project:delete": "Delete projects",
    "portfolio:create": "Create portfolios",
    "portfolio:read": "View portfolios",
    "portfolio:update": "Modify portfolios",
    "portfolio:delete": "Delete portfolios",
    "program:create": "Create programs",
    "program:read": "View programs",
    "program:update": "Modify programs",
    "program:delete": "Delete programs",
    "task:create": "Create tasks",
    "task:read": "View tasks",
    "task:update": "Modify tasks",
    "task:delete": "Delete tasks",
    "sprint:create": "Create sprints",
    "sprint:read": "View sprints",
    "sprint:update": "Modify sprints",
    "sprint:delete": "Delete sprints",
    "resource:create": "Create resources",
    "resource:read": "View resources",
    "resource:update": "Modify resources and allocations",
    "resource:delete": "Delete resources",
    "finance:create": "Create financial entries",
    "finance:read": "View financials",
    "finance:update": "Modify financial entries",
    "finance:delete": "Delete financial entries",
    "risk:create": "Create risks",
    "risk:read": "View risks",
    "risk:update": "Modify risks",
    "risk:delete": "Delete risks",
    "issue:create": "Create issues",
    "issue:read": "View issues",
    "issue:update": "Modify issues",
    "issue:delete": "Delete issues",
    "raid:create": "Create RAID actions and decisions",
    "raid:read": "View RAID log",
    "raid:update": "Modify RAID actions and decisions",
    "raid:delete": "Delete RAID actions and decisions",
    "change:create": "Create change requests",
    "change:read": "View change requests",
    "change:update": "Modify change requests",
    "change:approve": "Approve or reject change requests",
    "change:delete": "Delete change requests",
    "dependency:create": "Create dependencies",
    "dependency:read": "View dependencies",
    "dependency:update": "Modify dependencies",
    "dependency:delete": "Delete dependencies",
    "milestone:create": "Create milestones",
    "milestone:read": "View milestones",
    "milestone:update": "Modify milestones",
    "milestone:delete": "Delete milestones",
    "milestone:accept": "Accept deliverables and release milestone payments",
    "projectkpi:read": "View per-project KPIs",
    "projectkpi:manage": "Create, update and delete per-project KPIs",
    "timesheet:create": "Log time entries",
    "timesheet:read": "View time entries",
    "timesheet:update": "Modify time entries",
    "timesheet:approve": "Approve or reject time entries",
    "timesheet:delete": "Delete time entries",
    "document:create": "Upload documents",
    "document:read": "View documents",
    "document:update": "Modify document metadata",
    "document:delete": "Delete documents",
    "meeting:create": "Create meetings",
    "meeting:read": "View meetings",
    "meeting:update": "Modify meetings and attendees",
    "meeting:delete": "Delete meetings",
    "notification:create": "Send notifications to users",
    "notification:read": "View own notifications",
    "notification:update": "Manage own notifications and preferences",
    "notification:delete": "Delete own notifications",
    "report:create": "Create report definitions",
    "report:read": "View and run reports",
    "report:update": "Modify report definitions",
    "report:delete": "Delete report definitions",
    "dashboard:create": "Create dashboards",
    "dashboard:read": "View and render dashboards",
    "dashboard:update": "Modify dashboards and widgets",
    "dashboard:delete": "Delete dashboards",
    "copilot:use": "Use the AI copilot assistant",
    "admin:read": "View audit logs, admin overview and diagnostics",
    "admin:manage": "Run administrative maintenance (permission reconciliation)",
    "intelligence:read": "View intelligence analytics (performance, EVM, health)",
    "benefit:read": "View benefits and realisation",
    "benefit:create": "Create benefits",
    "benefit:update": "Update benefits and record realisation",
    "benefit:delete": "Delete benefits",
    "skill:read": "View skills, the skills matrix and capacity",
    "skill:manage": "Manage skills and resource skill assignments",
    "initiative:read": "View strategic initiatives, goals and KPIs",
    "initiative:manage": "Manage strategic initiatives, goals and KPIs",
    "workflow:read": "View workflow definitions and instances",
    "workflow:manage": "Manage workflow definitions and run instances",
    "workflow:approve": "Record approval decisions at workflow gates",
    "vendor:read": "View vendors, contracts and purchase orders",
    "vendor:manage": "Manage vendors, contracts and purchase orders",
    "integration:read": "View webhooks and delivery logs",
    "integration:manage": "Manage webhooks and publish events",
    "apikey:manage": "Issue and revoke API keys",
    "build:read": "View AI delivery builds and pipeline runs",
    "build:manage": "Manage AI delivery builds and report pipeline runs",
    "sso:manage": "Configure single sign-on (OIDC)",
}

# Wildcard grants every permission in the catalogue.
_ALL = tuple(PERMISSION_CATALOGUE.keys())

SYSTEM_ROLES: dict[str, tuple[str, ...]] = {
    "Organization Admin": _ALL,
    "Project Manager": (
        "organization:read",
        "user:read",
        "role:read",
        "project:create",
        "project:read",
        "project:update",
        "portfolio:read",
        "portfolio:create",
        "portfolio:update",
        "program:read",
        "program:create",
        "program:update",
        "task:create",
        "task:read",
        "task:update",
        "task:delete",
        "sprint:create",
        "sprint:read",
        "sprint:update",
        "sprint:delete",
        "resource:create",
        "resource:read",
        "resource:update",
        "resource:delete",
        "finance:create",
        "finance:read",
        "finance:update",
        "finance:delete",
        "risk:create",
        "risk:read",
        "risk:update",
        "risk:delete",
        "issue:create",
        "issue:read",
        "issue:update",
        "issue:delete",
        "raid:create",
        "raid:read",
        "raid:update",
        "raid:delete",
        "change:create",
        "change:read",
        "change:update",
        "change:approve",
        "change:delete",
        "dependency:create",
        "dependency:read",
        "dependency:update",
        "dependency:delete",
        "milestone:create",
        "milestone:read",
        "milestone:update",
        "milestone:delete",
        "milestone:accept",
        "projectkpi:read",
        "projectkpi:manage",
        "timesheet:create",
        "timesheet:read",
        "timesheet:update",
        "timesheet:approve",
        "timesheet:delete",
        "document:create",
        "document:read",
        "document:update",
        "document:delete",
        "meeting:create",
        "meeting:read",
        "meeting:update",
        "meeting:delete",
        "notification:create",
        "notification:read",
        "notification:update",
        "notification:delete",
        "report:create",
        "report:read",
        "report:update",
        "report:delete",
        "dashboard:create",
        "dashboard:read",
        "dashboard:update",
        "dashboard:delete",
        "copilot:use",
        "intelligence:read",
        "benefit:read",
        "benefit:create",
        "benefit:update",
        "benefit:delete",
        "skill:read",
        "skill:manage",
        "initiative:read",
        "initiative:manage",
        "workflow:read",
        "workflow:manage",
        "workflow:approve",
        "vendor:read",
        "vendor:manage",
        "integration:read",
        "integration:manage",
        "build:read",
        "build:manage",
    ),
    "Member": (
        "organization:read",
        "user:read",
        "project:read",
        "portfolio:read",
        "program:read",
        "task:read",
        "task:update",
        "sprint:read",
        "resource:read",
        "finance:read",
        "risk:read",
        "issue:read",
        "issue:create",
        "issue:update",
        "raid:read",
        "raid:update",
        "change:read",
        "change:create",
        "dependency:read",
        "milestone:read",
        "projectkpi:read",
        "timesheet:create",
        "timesheet:read",
        "timesheet:update",
        "document:read",
        "document:create",
        "meeting:read",
        "meeting:create",
        "meeting:update",
        "notification:read",
        "notification:update",
        "notification:delete",
        "report:read",
        "report:create",
        "dashboard:read",
        "dashboard:create",
        "copilot:use",
        "intelligence:read",
        "benefit:read",
        "skill:read",
        "initiative:read",
        "workflow:read",
        "vendor:read",
        "integration:read",
        "build:read",
    ),
}

# The role automatically assigned to the first user of a new organization.
BOOTSTRAP_ADMIN_ROLE = "Organization Admin"
